- pom.xml
- src/main/java/jkube/operator/EventDispatcher.java
- src/main/java/jkube/operator/Operator.java
We want to support older version of java also. There are more smart way for that, but for now this is good enough.
> Now project is built using java 8

- operator-framework/pom.xml
- operator-framework/src/main/java/com/github/containersolutions/operator/Operator.java
- operator-framework/src/main/java/com/github/containersolutions/operator/processing/CustomResourceEvent.java
- operator-framework/src/main/java/com/github/containersolutions/operator/processing/EventScheduler.java
- operator-framework/src/main/java/com/github/containersolutions/operator/processing/EventStore.java
- operator-framework/src/main/java/com/github/containersolutions/operator/processing/retry/GenericRetry.java
- operator-framework/src/main/java/com/github/containersolutions/operator/processing/retry/GenericRetryExecution.java
- operator-framework/src/main/java/com/github/containersolutions/operator/processing/retry/Retry.java
- operator-framework/src/main/java/com/github/containersolutions/operator/processing/retry/RetryExecution.java
- operator-framework/src/test/java/com/github/containersolutions/operator/EventSchedulerTest.java
- operator-framework/src/test/java/com/github/containersolutions/operator/processing/retry/GenericRetryExecutionTest.java
- operator-framework/src/test/resources/log4j2.xml
- pom.xml
impl for issue:
https://github.com/ContainerSolutions/java-operator-sdk/issues/52
> Retry back off, our custom implementation

- operator-framework/src/main/java/com/github/containersolutions/operator/ControllerUtils.java
This pull request fixes the illegal access warnings issue and keeps the code running in Java 8. See #69.
> Fix the illegal access issue

- .github/workflows/release.yml
- operator-framework/src/main/java/com/github/containersolutions/operator/Operator.java
- this will be merged to master since it needs to be tested/further developed from there.
> Release with GitHub actions

- README.md
Just a few lines to get people started if they want to use Spring Boot. I don't have a ton of experience with Spring yet so please feel free to correct me, this is the way I got it working but wouldn't be surprised if there's a better way :slightly_smiling_face: 
Contributes to #84
> Add documentation for Spring Boot in Readme

- README.md
- docs/DOCS.md
Note that this is just a skeleton for the user guide, but if we start this was its easier to someone just pick up a section and do further PR-s
> User guide

- .gitignore
- docs/_includes/footer.html
- docs/_includes/header.html
- operator-framework/src/main/java/com/github/containersolutions/operator/ControllerUtils.java
- samples/mysql-schema/src/main/java/com/github/containersolutions/operator/sample/SchemaController.java
Few issues SonarQube pointed out.
> Some minor improvements

- operator-framework/pom.xml
- pom.xml
- spring-boot-starter/pom.xml
note: I had to explicitly add [junit-platform-commons]
due to an issue with Spring Boot and JUnit 5.x
https://stackoverflow.com/questions/54598484/gradle-5-junit-bom-and-spring-boot-incorrect-versions/54605523#54605523
> maven-surefire-plugin 3.0.0-M5

- CONTRIBUTING.md
Added the discord channel link for ease.
> updated a link

- .github/workflows/ci.yml
- .github/workflows/release.yml
- operator-framework/pom.xml
- samples/common/pom.xml
- samples/mysql-schema/README.md
- samples/mysql-schema/pom.xml
- samples/pure-java/pom.xml
- samples/spring-boot-auto-config/pom.xml
- samples/spring-boot-plain/pom.xml
- samples/tomcat/pom.xml
- samples/webserver/pom.xml
- spring-boot-starter/pom.xml
> Support only java version 11 and above!

- .github/workflows/master-snapshot-release.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
> Snapshot release

- operator-framework/src/main/java/io/javaoperatorsdk/operator/api/Context.java
- operator-framework/src/main/java/io/javaoperatorsdk/operator/api/DefaultContext.java
- operator-framework/src/main/java/io/javaoperatorsdk/operator/processing/DefaultEventHandler.java
- operator-framework/src/main/java/io/javaoperatorsdk/operator/processing/EventDispatcher.java
- operator-framework/src/main/java/io/javaoperatorsdk/operator/processing/event/AbstractEvent.java
- operator-framework/src/main/java/io/javaoperatorsdk/operator/processing/event/Event.java
- operator-framework/src/main/java/io/javaoperatorsdk/operator/processing/event/EventHandler.java
- operator-framework/src/main/java/io/javaoperatorsdk/operator/processing/event/EventList.java
- operator-framework/src/main/java/io/javaoperatorsdk/operator/processing/event/internal/CustomResourceEvent.java
- operator-framework/src/main/java/io/javaoperatorsdk/operator/processing/event/internal/TimerEvent.java
* EventList class introduced for convenient helper methods
* Event becomes non-generic
> * Event becomes non generic

- operator-framework-quarkus-extension/deployment/src/main/java/io/javaoperatorsdk/quarkus/extension/deployment/QuarkusExtensionProcessor.java
> Fixes an issue with the quarkus extension

- README.md
- operator-framework-spring-boot-starter-test/pom.xml
- operator-framework-spring-boot-starter-test/src/main/java/io/javaoperatorsdk/operator/springboot/starter/test/EnableMockOperator.java
- operator-framework-spring-boot-starter-test/src/main/java/io/javaoperatorsdk/operator/springboot/starter/test/TestConfiguration.java
- pom.xml
- samples/spring-boot-auto-config/pom.xml
- samples/spring-boot-auto-config/src/test/java/io/javaoperatorsdk/operator/sample/SpringBootStarterSampleApplicationIT.java
- samples/spring-boot-auto-config/src/test/java/io/javaoperatorsdk/operator/sample/SpringBootStarterSampleApplicationTest.java
- samples/spring-boot-auto-config/src/test/resources/application.yaml
- samples/spring-boot-auto-config/src/test/resources/test-crd.yaml
> Spring boot test module

- operator-framework-spring-boot-starter-test/src/main/java/io/javaoperatorsdk/operator/springboot/starter/test/EnableMockOperator.java
- operator-framework-spring-boot-starter-test/src/main/java/io/javaoperatorsdk/operator/springboot/starter/test/TestConfiguration.java
- operator-framework-spring-boot-starter-test/src/main/java/io/javaoperatorsdk/operator/springboot/starter/test/TestConfigurationProperties.java
- operator-framework-spring-boot-starter-test/src/test/resources/application.properties
- operator-framework-spring-boot-starter/src/main/java/io/javaoperatorsdk/operator/springboot/starter/KubernetesClientProperties.java
- operator-framework-spring-boot-starter/src/main/java/io/javaoperatorsdk/operator/springboot/starter/OperatorAutoConfiguration.java
- operator-framework-spring-boot-starter/src/main/java/io/javaoperatorsdk/operator/springboot/starter/OperatorConfigurationProperties.java
- operator-framework-spring-boot-starter/src/test/java/io/javaoperatorsdk/operator/springboot/starter/AutoConfigurationTest.java
- operator-framework-spring-boot-starter/src/test/resources/application.yaml
- samples/spring-boot-auto-config/src/main/resources/application.yaml
- samples/spring-boot-auto-config/src/test/resources/application.yaml
- samples/spring-boot-plain/src/main/resources/application.yaml
This PR renames the spring properties from **io.javaoperatorsdk** to **javaoperatorsdk**!
> Spring properties naming

- operator-framework/src/main/java/io/javaoperatorsdk/operator/config/runtime/ControllerAnnotationProcessor.java
- operator-framework/src/test/resources/compile-fixtures/ControllerImplemented2InterfacesExpected.java
- operator-framework/src/test/resources/compile-fixtures/ControllerImplementedIntermediateAbstractClassExpected.java
- operator-framework/src/test/resources/compile-fixtures/MultilevelControllerExpected.java
Fix uncheck warnings.
closes #274
> Fix uncheck warnings

- operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/internal/TimerEventSourceTest.java
this should be an easy one to review :D
> Increase test timer slack time to make test not fail

- samples/common/src/main/java/io/javaoperatorsdk/operator/sample/CustomServiceController.java
> remove unnecessary delete code from deleteResource sample

- README.md
New links on medium, where I will maintain these blog posts.
> update blog links

- operator-framework-quarkus-extension/deployment/src/main/java/io/javaoperatorsdk/quarkus/extension/deployment/QuarkusExtensionProcessor.java
- operator-framework-quarkus-extension/tests/pom.xml
- operator-framework-quarkus-extension/tests/src/main/java/io/javaoperatorsdk/quarkus/it/AbstractController.java
- operator-framework-quarkus-extension/tests/src/main/java/io/javaoperatorsdk/quarkus/it/ChildTestResource.java
- operator-framework-quarkus-extension/tests/src/main/java/io/javaoperatorsdk/quarkus/it/ConfiguredController.java
- operator-framework-quarkus-extension/tests/src/main/java/io/javaoperatorsdk/quarkus/it/TestController.java
- operator-framework-quarkus-extension/tests/src/test/java/io/javaoperatorsdk/quarkus/it/QuarkusExtensionProcessorTest.java
> fix: do not run extension on abstract controllers

- operator-framework-quarkus-extension/pom.xml
- samples/quarkus/pom.xml
> chore: upgrade to Quarkus 1.12.1

- README.md
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/Utils.java
- operator-framework-quarkus-extension/deployment/src/main/java/io/javaoperatorsdk/quarkus/extension/deployment/QuarkusExtensionProcessor.java
- operator-framework-quarkus-extension/runtime/src/main/java/io/javaoperatorsdk/quarkus/extension/ConfigurationServiceRecorder.java
- operator-framework-quarkus-extension/runtime/src/main/java/io/javaoperatorsdk/quarkus/extension/ExternalConfiguration.java
- operator-framework-quarkus-extension/runtime/src/main/java/io/javaoperatorsdk/quarkus/extension/ExternalControllerConfiguration.java
- operator-framework-quarkus-extension/runtime/src/main/java/io/javaoperatorsdk/quarkus/extension/QuarkusConfigurationService.java
- operator-framework-quarkus-extension/tests/src/main/java/io/javaoperatorsdk/quarkus/it/TestOperatorApp.java
- operator-framework-quarkus-extension/tests/src/main/resources/application.properties
- operator-framework-quarkus-extension/tests/src/test/java/io/javaoperatorsdk/quarkus/it/QuarkusExtensionProcessorTest.java
- operator-framework/src/main/java/io/javaoperatorsdk/operator/config/runtime/DefaultConfigurationService.java
> feat: make it possible to deactivate CR validation

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/ResourceController.java
- make deleteResource a default method
- update the doc to reflect the actual code
> Improve ResourceController

- operator-framework/pom.xml
- pom.xml
- samples/common/pom.xml
- samples/quarkus/pom.xml
fabric8 kubernetes-client -> 5.2.1
Quarkus -> 1.12.2
> Dependencies update

- docs/DOCS.md
Signed-off-by: Jeesmon Jacob <jjacob@us.ibm.com>
> Update broken example link

- samples/README.md
Make it easy for people to find the good samples
> add readme to samples

- operator-framework-core/src/test/java/io/javaoperatorsdk/operator/CustomResourceUtilsTest.java
> Separate CRUtils test cases

- .github/ISSUE_TEMPLATE/bug-report.md
As discussed in today's community meeting, added issue template for bug report.
> Issue template for bug report.

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
> Change server version error to exception rather that system stop call

- .github/workflows/master-snapshot-release.yml
- .github/workflows/pr.yml
- chore(ci): update minikube and kubernetes version
> GitHub Actions: update kubernetes & minikbe version"

- .github/workflows/master-snapshot-release.yml
- .github/workflows/pr.yml
- chore(ci): limit job concurrency
- chore(ci): add support for manual triggers
> Tweak GitHub Actions

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
> feat: don't install a shutdown hook by default

- .github/workflows/master-snapshot-release.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .mvn/wrapper/MavenWrapperDownloader.java
- .mvn/wrapper/maven-wrapper.properties
- mvnw
- mvnw.cmd
This is to be sure the build is independent from the maven version provided by the GitHub Action environment
> chore: add maven wrapper for bettere reproducibility

- operator-framework-core/src/test/resources/log4j2.xml
- operator-framework/src/test/resources/log4j2.xml
- samples/common/src/main/resources/log4j2.xml
> disable colors in test logs

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/internal/TimerEventSource.java
- operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/internal/TimerEventSourceTest.java
> fix: stop timers when closing TimerEventSources

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverrider.java
- samples/pure-java/src/main/java/io/javaoperatorsdk/operator/sample/PureJavaApplicationRunner.java
> feat: make it easier to override ConfigurationService

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/DefaultEvent.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/internal/InformerEvent.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/internal/InformerEventSource.java
- operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/OperatorExtension.java
- operator-framework/src/test/java/io/javaoperatorsdk/operator/InformerEventSourceIT.java
- operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/informereventsource/InformerEventSourceTestCustomResource.java
- operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/informereventsource/InformerEventSourceTestCustomResourceController.java
- operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/informereventsource/InformerEventSourceTestCustomResourceSpec.java
- operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/informereventsource/InformerEventSourceTestCustomResourceStatus.java
see: https://github.com/java-operator-sdk/java-operator-sdk/issues/564
> Informer event source

- sample-operators/tomcat-operator/src/main/java/io/javaoperatorsdk/operator/sample/TomcatReconciler.java
- sample-operators/tomcat-operator/src/main/java/io/javaoperatorsdk/operator/sample/WebappReconciler.java
- sample-operators/tomcat-operator/src/main/resources/io/javaoperatorsdk/operator/sample/service.yaml
- use informer cache instead read from API server
- use owner reference instead of delete
> refactor: tomcat example improvements

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/DefaultContext.java
- operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/CustomResourceSelectorTest.java
- fix: Optional associated resource
- fix: enable test
- fix: fomrat
- refactor: simplify
> refactor: simplify

- .github/workflows/snapshot-releases.yml
This should be cherry-picked to `main` as well.
> chore(ci): rename snapshots workflow, add next, only keep unit tests

- .mvn/wrapper/maven-wrapper.properties
- mvnw
- mvnw.cmd
https://maven.apache.org/wrapper/index.html
https://github.com/apache/maven-wrapper
https://twitter.com/jvanzyl/status/1472199110866481159
﻿
> use official Maven Wrapper 

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/Utils.java
- operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/UtilsTest.java
> fix: debugThreadPool & shouldCheckCRDAndValidateLocalModel should work

- operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/InClusterCurl.java
> More flexible in cluster curl

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/AnnotationControllerConfiguration.java
> fix: config needs to be reset for each dependent

- operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/OperatorExtension.java
- sample-operators/mysql-schema/src/test/java/io/javaoperatorsdk/operator/sample/MySQLSchemaOperatorE2E.java
> feat(junit): allow to forward port of local pods

- docs/documentation/architecture-and-internals.md
As I read `architecture and internals` document, I think I found some typo.
> fix architecture-and-internals document

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/AnnotationControllerConfiguration.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ControllerConfiguration.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ControllerConfigurationOverrider.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/DefaultControllerConfiguration.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependent.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResource.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResourceConfig.java
- operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/ControllerConfigurationOverriderTest.java
- operator-framework/src/test/java/io/javaoperatorsdk/operator/config/runtime/AnnotationControllerConfigurationTest.java
> fix: namespaces overriding should propagate to dependents if needed

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/AnnotationControllerConfiguration.java
- operator-framework/src/test/java/io/javaoperatorsdk/operator/config/runtime/AnnotationControllerConfigurationTest.java
> fix: homogenize label selector default value

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/ReconcilerUtils.java
> refactor: use fabric8 finalizer validation

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/ReconcilerUtils.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/Controller.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/controller/ControllerResourceEventSource.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerWrapper.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/timer/TimerEventSource.java
- operator-framework-core/src/test/java/io/javaoperatorsdk/operator/ReconcilerUtilsTest.java
- fix: start timer as daemon to avoid prolonging the app's life
- fix: exit operator on exception when starting
> fix: shut down operator when failing to start

- .github/workflows/e2e-test.yml
- .github/workflows/pr.yml
- .github/workflows/snapshot-releases.yml
- .github/workflows/sonar.yml
Skip CI runs when changes are only made to docs directory.
ref: [issue #835]
> ci : change workflow logic

- sample-operators/webpage/k8s/webpage.yaml
- sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/ConfigMapDependentResource.java
- sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageReconciler.java
> docs: why the pods deleted on web page sample

- .github/workflows/release-project-in-dir.yml
- .github/workflows/release.yml
- micrometer-support/pom.xml
- operator-framework-bom/pom.xml
- operator-framework-core/pom.xml
- operator-framework-junit5/pom.xml
- operator-framework/pom.xml
- pom.xml
- sample-operators/leader-election/pom.xml
- sample-operators/mysql-schema/pom.xml
- sample-operators/pom.xml
- sample-operators/tomcat-operator/pom.xml
- sample-operators/webpage/pom.xml
- fix: add missing project information
- feat: add reusable workflow to be able to release both project and BOM
- chore: update version to 4.0.0-SNAPSHOT
> chore: prepare for 4.0.0 release

- pom.xml
This reverts commit 6cca81e02e9439b85121f37026387e7bfa8fdad0.
> Revert "chore: use s01 server which should be less prone to timeouts (#1486)"

- operator-framework-bom/pom.xml
- pom.xml
the only purpose of the this PR is to trigger snapshot release of main
> fix: bom version on main

- README.md
Adding "Locust k8s operator" to the list of example projects
> docs: Add Locust k8s operator to list of projects

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverrider.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/InformerStoppedHandler.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerWrapper.java
- operator-framework-core/src/test/java/io/javaoperatorsdk/operator/MockKubernetesClient.java
- operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverriderTest.java
- operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerEventSourceTest.java
- operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/AbstractOperatorExtension.java
- operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/ClusterDeployedOperatorExtension.java
- operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/LocallyRunOperatorExtension.java
- operator-framework/src/test/java/io/javaoperatorsdk/operator/MultiVersionCRDIT.java
- pom.xml
**DO NOT MERGE before Fabric8 Client 6.2.0 is released.**
> feat: enable configuring a handler to listen to informers stopping

- .github/workflows/e2e-test.yml
- .github/workflows/pr.yml
This reverts commit 3e44a8dfc0cd869545fd1da71b08aeebd3b0eea1.
> Revert "chore(deps): bump manusa/actions-setup-minikube from 2.7.1 to 2.7.2"

- docs/documentation/patterns-best-practices.md
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/AggregatedOperatorException.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/EventSourceInitializer.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/DependentResource.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/AbstractExternalDependentResource.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventSourceManager.java
- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventSourceRetriever.java
- operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/externalstate/externalstatebulkdependent/BulkDependentResourceExternalWithState.java
- feat: provide more exception context on workflow errors
- refactor: simplify
- docs: improve wording
> feat: provide more exception context on workflow errors

- .github/workflows/e2e-test.yml
- .github/workflows/pr.yml
This fixes also issue with minikube. If started twice in a job, it causes issues.
> fix: separated job with special integration tests

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/Mappers.java
We use code similar to this so I figured I would contribute it back upstream. There is a mapper already that will look at owner references but it only handles a single reference and doesn't compare the kind.
> feat: add a mapper that is based on owner reference kind

- docs/documentation/dependent-resources.md
Dependent resource are fairly stable for a while
> docs: remove dependent resources disclaimer

- .github/workflows/e2e-test.yml
- .github/workflows/pr.yml
> chore: update Kubernetes versions to latest

- caffeine-bounded-cache-support/pom.xml
- micrometer-support/pom.xml
- operator-framework-bom/pom.xml
- operator-framework-core/pom.xml
- operator-framework-junit5/pom.xml
- operator-framework/pom.xml
- pom.xml
- sample-operators/leader-election/pom.xml
- sample-operators/mysql-schema/pom.xml
- sample-operators/pom.xml
- sample-operators/tomcat-operator/pom.xml
- sample-operators/webpage/pom.xml
There was a problem with the latest release, version update action did not run properly.
> fix: snapshot version update

- .github/workflows/snapshot-releases.yml
see problem: https://github.com/operator-framework/java-operator-sdk/actions/runs/6495284343/job/17639939661
> fix: snapshot build

- pom.xml
> chore: update to Fabric8 client 6.9.2

- .github/workflows/pr.yml
Add kubernetes v1.29.0 to CI for PR.
> CI with kubernetes v1.29.0

- pom.xml
> fix: update SCM information

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/ManagedWorkflowSupport.java
> refactor: make ManagedWorkflowSupport public to be able to reuse it

- pom.xml
> chore: update to Fabric8 client 6.12.1

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/AbstractDependentResource.java
Moved existing debug log message and added new debug log message.
> chore: adjust debug logs for updating a dependent resource

- bootstrapper-maven-plugin/src/main/resources/templates/pom.xml
> fix: remove duplicated dependency

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/GroupVersionKind.java
> fix: improper javadoc preventing release

- pom.xml
> chore(deps): upgrade to fabric8 client 6.13.1

- pom.xml
> chore(deps): update Fabric8 client to 6.13.2

- .gitignore
> improve: add .java-version to gitignore

- .github/ISSUE_TEMPLATE/enhancement-request.md
Added github issue template for creating enhancement issues
- Closes issue #2507
> chore: added github issue template for creating enhancement issues

- .github/workflows/e2e-test.yml
- .github/workflows/fabric8-next-version-schedule.yml
- .github/workflows/pr.yml
> chore(ci): update kubernetes versions

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/BooleanWithUndefined.java
> refactor: make asBoolean public

- pom.xml
> chore: update to Fabric8 client 6.13.4

- README.md
> docs: add spark operator for to operator list

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverrider.java
> fix: typo in withParseResourceVersions

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventSources.java
- operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/EventSourcesTest.java
> fix: concurrent modification when getting event sources (v4)

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/DefaultManagedWorkflow.java
- operator-framework/src/test/java/io/javaoperatorsdk/operator/workflow/complexdependent/ComplexWorkflowIT.java
> refactor: minor

- docs/content/en/blog/releases/v5-release.md
Update docs/content/en/blog/releases/v5-release.md
> docs: release 5 blogpost

- .github/workflows/release.yml
> fix: use updated output syntax

- docs/content/en/blog/releases/v5-release.md
> docs: all changes link

- docs/content/en/blog/releases/v5-release.md
> docs: fix blod date

- .github/workflows/release.yml
> fix: release action for v5

- pom.xml
> chore: use fabric8 7.0.1

- docs/content/en/docs/dependent-resources/_index.md
> docs: fix dependent resources double title

- sample-operators/leader-election/src/test/java/io/javaoperatorsdk/operator/sample/LeaderElectionE2E.java
> fix: leader election e2e test

- docs/content/en/blog/releases/v5-release-beta1.md
- docs/content/en/blog/releases/v5-release.md
- **docs: non beta blogpost**
- **wip**
> updated blog link

- docs/content/en/blog/releases/v5-release.md
> docs: fix release date on blog

- docs/content/en/blog/news/etcd-as-app-db.md
Hi :wave: !
I have had to answer this question quite many times now, so I wrote it down as a general FAQ ...
I'm considering where to publish it, and this Blog looks like a possible place to land it.
Happy to hear feedback about the content and where is most appropriate to publish it!
> Blog: using ETCD as app DB

- pom.xml
> chore: update Fabric8 client to 7.1.0

- docs/content/en/blog/releases/v5-release.md
> docs: v5 release notes facelift

- bootstrapper-maven-plugin/src/test/java/io/javaoperatorsdk/bootstrapper/BootstrapperTest.java
> fix: release process of bootstrapper

- bootstrapper-maven-plugin/pom.xml
- caffeine-bounded-cache-support/pom.xml
- micrometer-support/pom.xml
- operator-framework-bom/pom.xml
- operator-framework-core/pom.xml
- operator-framework-junit5/pom.xml
- operator-framework/pom.xml
- pom.xml
- sample-operators/controller-namespace-deletion/pom.xml
- sample-operators/leader-election/pom.xml
- sample-operators/mysql-schema/pom.xml
- sample-operators/pom.xml
- sample-operators/tomcat-operator/pom.xml
- sample-operators/webpage/pom.xml
> chore: set version to 5.0.1-SNAPSHOT

- OWNERS
I don't know who to keep or to remove, so please tell me if any further updates are needed.
> chore: update OWNERS for the current state of the project

- docs/content/en/blog/news/nonssa-vs-ssa.md
> docs: add author to blog post

- sample-operators/mysql-schema/pom.xml
> bump mysql connector

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/GenericKubernetesDependentResource.java
> improve: allow to provide name to GenericKubernetesDependentResource

- docs/content/en/_index.md
- docs/hugo.toml
> docs: social access facelift

- operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventProcessor.java
> fix: typos

- .github/workflows/build.yml
- .github/workflows/e2e-test.yml
- .github/workflows/integration-tests.yml
> chore(CI): bump minikube and kubernetes versions

- pom.xml
> chore: fabric8 client to v7.3

- bootstrapper-maven-plugin/pom.xml
- caffeine-bounded-cache-support/pom.xml
- micrometer-support/pom.xml
- operator-framework-bom/pom.xml
- operator-framework-core/pom.xml
- operator-framework-junit5/pom.xml
- operator-framework/pom.xml
- pom.xml
- sample-operators/controller-namespace-deletion/pom.xml
- sample-operators/leader-election/pom.xml
- sample-operators/mysql-schema/pom.xml
- sample-operators/pom.xml
- sample-operators/tomcat-operator/pom.xml
- sample-operators/webpage/pom.xml
> chore(build): update version to 5.1.0-SNAPSHOT

- operator-framework-bom/pom.xml
> fix: remove staging plugin from bom module

- operator-framework-bom/pom.xml
> fix: put back version for bom in release

- operator-framework-bom/pom.xml
- pom.xml
> fix: source plugin for release

- operator-framework-bom/pom.xml
> fix: remove source plugin from bom release

- operator-framework-bom/pom.xml
- pom.xml
> fix: release and snapshot release

- operator-framework/src/test/java/io/javaoperatorsdk/operator/dependent/createonlyifnotexistsdependentwithssa/CreateOnlyIfNotExistingDependentWithSSAIT.java
> docs: comment to clarify SSA usage in CreateOnlyIfNotExistingDependentWithSSAIT

- pom.xml
> chore(deps): update to Fabric8 client 7.4.0
