operator-framework/src/main/java/com/github/containersolutions/operator/Operator.java
operator-framework/src/main/java/com/github/containersolutions/operator/processing/EventDispatcher.java
operator-framework/src/test/java/com/github/containersolutions/operator/EventDispatcherTest.java

…ustom resource target namespace

fix for issues, when we are having different default namespace then custom resource namespace

---

operator-framework/src/main/java/com/github/containersolutions/operator/Operator.java

Currently, the `getCustomResourceClients(Class<T> crc)` method returns a raw version of the CustomResourceOperationsImpl object, so it is not possible to call the `getItems()` method when you want a list of all your custom resources:
```java
List<MyCR> crs = operator.getCustomResourceClients(MyCR.class)
.inNamespace("default")
.list()
.getItems();
```
This pull request modifies the `getCustomResourceClients(Class<T> crc)` method to return a parameterized version of the CustomResourceOperationsImpl object to make this possible.

Return a parameterized version of the CustomResourceOperationsImpl object

---

operator-framework/src/main/java/com/github/containersolutions/operator/ControllerUtils.java
operator-framework/src/main/java/com/github/containersolutions/operator/Operator.java
operator-framework/src/main/java/com/github/containersolutions/operator/api/Controller.java
operator-framework/src/main/java/com/github/containersolutions/operator/processing/EventScheduler.java
operator-framework/src/main/java/com/github/containersolutions/operator/processing/EventStore.java
operator-framework/src/test/java/com/github/containersolutions/operator/ConcurrencyIT.java
operator-framework/src/test/java/com/github/containersolutions/operator/ControllerExecutionIT.java
operator-framework/src/test/java/com/github/containersolutions/operator/ControllerUtilsTest.java
operator-framework/src/test/java/com/github/containersolutions/operator/EventSchedulerTest.java
operator-framework/src/test/java/com/github/containersolutions/operator/IntegrationTestSupport.java
operator-framework/src/test/java/com/github/containersolutions/operator/sample/TestCustomResourceController.java
operator-framework/src/test/resources/com/github/containersolutions/operator/test-crd.yaml

Will process events only if generation attribute is increased from last execution. (Configurable with flag)

Generation aware scheduling

---

operator-framework/src/main/java/com/github/containersolutions/operator/processing/EventScheduler.java
operator-framework/src/main/java/com/github/containersolutions/operator/processing/EventStore.java
operator-framework/src/test/java/com/github/containersolutions/operator/ControllerExecutionIT.java

This is a fix for an issue with the new generation aware scheduling for retries, when we received an update which did not increased the generation while a controller was in execution and tried to do an update.

fix for generation aware retries issue

---

samples/mysql-schema/k8s/crd.yaml
samples/mysql-schema/src/main/java/com/github/containersolutions/operator/sample/MySQLSchemaOperator.java
samples/mysql-schema/src/main/java/com/github/containersolutions/operator/sample/SchemaController.java
samples/mysql-schema/src/main/java/com/github/containersolutions/operator/sample/SchemaSpec.java
samples/mysql-schema/src/main/java/com/github/containersolutions/operator/sample/SchemaStatus.java

This patch addresses https://github.com/ContainerSolutions/java-operator-sdk/issues/113 by creating a predictable MySQL user with granted privileges over the created schema. The credentials are stored as a K8s secret in the namespace where the schema is created.

Store mysql credentials in k8s secret

---

CONTRIBUTING.md

Have a look and see what you think. There are some notes about getting started etc that you might want to modify.

First draft of contributing guidelines.

---

samples/mysql-schema/src/main/java/com/github/containersolutions/operator/sample/SchemaController.java

Use `PreparedStatement`s where possible in the `SchemaController` in order to avoid SQL Injections.
Note that `PreparedSatement`s can only dynamically bind values and not object names, so this technique could only be applied to the queries, and not the DDL statements. The security around these statements can probably be improved by sanitizing the schema values, but it's out of the scope of this PR.
As a side bonus, this PR also uses the try-with-resource idiom when creating these `PreparedStatement`s and `ResultSet`s so they will be properly closed instead of the current implementation that may leak resources.
Closes #120

SchemaController: User PreparedStatements where possible

---

README.md

Hope this is what you wanted!!
Else let me know... I'll ammend.

Hope it fulfills the issue!!

---

samples/common/src/main/java/io/javaoperatorsdk/operator/sample/CustomServiceController.java

When deleting, we have to use the same name as used in creating the service

Fixed deleting on the wrong name

---

.github/workflows/ci.yml
pom.xml

Run integration tests on every build

---

README.md

Hello,
Just fixing 2 typos that I saw when reading.
Best,
Didier

README.md: fixing a couple of typos

---

.github/workflows/ci.yml
operator-framework/src/main/java/io/javaoperatorsdk/operator/ControllerUtils.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/api/Controller.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/api/ResourceController.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/processing/EventDispatcher.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/ControllerExecutionIT.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/ControllerUtilsTest.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/EventDispatcherTest.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/EventSchedulerTest.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/IntegrationTestSupport.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/SubResourceUpdateIT.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/TestCustomResourceController.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/subresource/SubResourceTestCustomResourceController.java

Controller name as finalizer by default

---

README.md
operator-framework/pom.xml
operator-framework/src/main/java/io/javaoperatorsdk/operator/ControllerToCustomResourceMappingsProvider.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/ControllerUtils.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/api/Controller.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/processing/ControllerAnnotationProcessor.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/ControllerUtilsTest.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/processing/ControllerAnnotationProcessorTest.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/TestCustomResourceController.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/subresource/SubResourceTestCustomResourceController.java
operator-framework/src/test/resources/AbstractController.java
operator-framework/src/test/resources/ControllerImplemented2Interfaces.java
operator-framework/src/test/resources/ControllerImplemented2InterfacesExpected.java
operator-framework/src/test/resources/ControllerImplementedIntermediateAbstractClass.java
operator-framework/src/test/resources/ControllerImplementedIntermediateAbstractClassExpected.java
samples/common/src/main/java/io/javaoperatorsdk/operator/sample/CustomServiceController.java
samples/mysql-schema/src/main/java/io/javaoperatorsdk/operator/sample/SchemaController.java
samples/tomcat/src/main/java/io/javaoperatorsdk/operator/sample/TomcatController.java
samples/tomcat/src/main/java/io/javaoperatorsdk/operator/sample/WebappController.java
samples/webserver/src/main/java/io/javaoperatorsdk/operator/sample/WebServerController.java
spring-boot-starter/src/test/java/io/javaoperatorsdk/operator/spingboot/starter/TestController.java
spring-boot-starter/src/test/java/io/javaoperatorsdk/operator/springboot/starter/TestController.java

@kirek007 Here is the PoC.
You should be able to run the https://github.com/java-operator-sdk/basic-native-operator-example/tree/init with this version of the SDK with no need to define neither the donable class nor the custom resource class in @Controller annotation.
closes #224

Native Image Friendly

---

operator-framework/src/main/java/io/javaoperatorsdk/operator/ControllerToCustomResourceMappingsProvider.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/ControllerUtils.java

In circumstances that the classpath is not flat the current class/resource loading fails. 
I encountered this problem by running an operator with `quarkus:dev`.

Fix resource/class loading in environments with hierarchical Classpath

---

operator-framework/src/main/java/io/javaoperatorsdk/operator/processing/annotation/ControllerAnnotationProcessor.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/processing/annotation/ControllersResourceWriter.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/processing/annotation/ControllerAnnotationProcessorTest.java

Fix incremental compilation issue

---

operator-framework-spring-boot-starter-test/pom.xml
operator-framework-spring-boot-starter-test/src/main/java/io/javaoperatorsdk/operator/springboot/starter/test/EnableMockOperator.java
operator-framework-spring-boot-starter-test/src/main/java/io/javaoperatorsdk/operator/springboot/starter/test/TestConfiguration.java
operator-framework-spring-boot-starter-test/src/main/java/io/javaoperatorsdk/operator/springboot/starter/test/TestConfigurationProperties.java
operator-framework-spring-boot-starter-test/src/test/java/io/javaoperatorsdk/operator/springboot/starter/test/EnableMockOperatorTests.java
operator-framework-spring-boot-starter-test/src/test/resources/application.properties
operator-framework-spring-boot-starter-test/src/test/resources/crd.yml
operator-framework-spring-boot-starter-test/src/test/resources/global-crd.yml

Updated the testing support for spring boot integration so the mocked kubernetes can be configured solely via the annotation.
#261

Simplify testing support for spring boot

---

.github/workflows/master-snapshot-release.yml
.github/workflows/pr.yml

Upgrade `manusa/actions-setup-minikube` to use the latest version.
GitHub is rolling out Ubuntu 20.04 as the default environment. GitHub actions workflows using `ubuntu-latest` will [soon ](https://github.com/actions/virtual-environments/issues/1816) start an Ubuntu 20,04 instance instead of 18.04.
Prior versions of `manusa/actions-setup-minikube` have a check which won't allow the workflow job to run. Starting on `2.2.0`, Ubuntu 20.04 is supported too (https://github.com/manusa/actions-setup-minikube/issues/26).

Bump actions-setup-minikube to v2.3.0

---

README.md

The existing documentation doesn't explain the requirement to configure the SDK as an annotation processor in Gradle, as per https://github.com/java-operator-sdk/java-operator-sdk/issues/274. This PR adds an example to the usage section of the main README.

Add Gradle usage example to main README

---

README.md

This trivial PR just fixes a markdown mistake on adding the link to the Quarkus dependency.

Fixed link to Quarkus dependency

---

operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/internal/TimerEventSourceTest.java

Fixing this will taken a bit more time, so let's unblock verification of new quarkus and fabric8 until that's done

Disable unit tests for TimerEventSource

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/CustomResourceUtils.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/CustomResourceUtilsTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/TestUtils.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/sample/simple/NamespacedTestCustomResource.java

fix: add scope validation on custom resource

---

operator-framework-quarkus-extension/deployment/pom.xml
operator-framework-quarkus-extension/runtime/pom.xml
operator-framework-quarkus-extension/tests/pom.xml
samples/quarkus/src/main/java/io/javaoperatorsdk/operator/sample/QuarkusOperator.java

fix: make it possible to inject OpenShiftClient instead of plain k8s

---

README.md
operator-framework-spring-boot-starter/src/main/java/io/javaoperatorsdk/operator/springboot/starter/OperatorAutoConfiguration.java
operator-framework-spring-boot-starter/src/main/java/io/javaoperatorsdk/operator/springboot/starter/OperatorConfigurationProperties.java

Add the property `javaoperatorsdk.check-crd-and-validate-local-model` to control whether CustomResource implementations are validated.
Addressing https://github.com/java-operator-sdk/java-operator-sdk/issues/380

Make CustomResource implementations validation configurable for Spring Boot

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/Controller.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ControllerConfiguration.java

This is achieved by using `JOSDK_WATCH_CURRENT` as the only value of the
namespaces configuration for the controller.
Fixes #372

feat: Controllers can now watch only the namespace they're deployed in

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/CustomResourceCache.java
operator-framework-spring-boot-starter/src/main/java/io/javaoperatorsdk/operator/springboot/starter/OperatorAutoConfiguration.java

* Optionally provide the ObjectMapper in the constructor of the Operator
* Optionally provide the ObjectMapper in constructor of the CustomResourceCache
* Optionally autowire a ObjectMapper in spring boot

Make ObjectMapper of CustomResourceCache configurable

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/EventDispatcher.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/ExecutionScope.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/EventDispatcherTest.java

It turns out that completely removing `CustomResourceFacade` is more work than is worth. This PR thus limits its exposure by making it only accessible from the defining package so that it can still be used to control tests but doesn't unnecessarily "pollute" the rest of the code.
Also took the opportunity to make `EventDispatcher` and `ExecutionScope` parameterized so that it's clearer that they work with a single type of resource.
Fixes #389.

Hide CustomResourceFacade, make EventDispatcher & ExecutionScope parameterized

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/internal/CustomResourceEventSource.java

This is one of my proposed fixes for https://github.com/java-operator-sdk/java-operator-sdk/issues/395

fix: if a watch closes and fails to reconnect, exit the operator

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/DefaultEventHandler.java
operator-framework-spring-boot-starter/src/main/java/io/javaoperatorsdk/operator/springboot/starter/OperatorAutoConfiguration.java
operator-framework-spring-boot-starter/src/main/java/io/javaoperatorsdk/operator/springboot/starter/OperatorConfigurationProperties.java

feat: make reconciliation thread number configurable

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/DefaultEventHandler.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/DefaultEventSourceManager.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventHandler.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventSourceManager.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/internal/CustomResourceEventSource.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/internal/CustomResourceEventSourceTest.java

This PR includes:
- add lifecycle hooks to EventSource (#368)
- review DefaultEventSourceManager instance variable modifiers
- make DefaultEventSourceManager::registerEventSource final as it is invoked by the constructor
- DefaultEventSourceManager use containsKey instead of null check to determine if an event source is already registerd
- add lifecycle hooks to the operator so i.e. watchers can be properly closed
Fixes #368

Enhance event handling

---

README.md
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/Controller.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/ResourceController.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ControllerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/DefaultEventHandler.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/EventDispatcher.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/EventDispatcherTest.java

feat: make it possible to not automatically add finalizers

---

README.md
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/DefaultEventHandler.java

feat: add possibility to configure termination timeout

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/DefaultEventHandler.java

Event handler waits a long time before terminating

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ControllerConfiguration.java

feat: fail if current namespaces is required but cannot be resolved

---

docs/_includes/analytics.html
docs/_layouts/default.html
docs/_layouts/homepage.html

This PR adds Google Analytics to the website. I think it would be useful to get an idea of how many people are visiting the site. The analytics currently goes to Container Solutions.
This is just a proposal currently, please let me know if there are any concerns or issues.
I've not used the website generator before, so I may have made a mistake in there.

Add analytics to website.

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/CustomResourceUtils.java

This stream filtering implementation is basically the same as using List.contains(), and any performance differences might be negligible since we are just seeing if dependent classes are namespaced (there shouldn't be _that_ many of them).

Change stream implementation to List.contains()

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/CustomResourceCache.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/DefaultEventHandler.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/EventBuffer.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/AbstractEvent.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/DefaultEventSourceManager.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/Event.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/CustomResourceSelectorTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/DefaultEventHandlerTest.java

feat: use a predicate to select the custom resource for which a reconcile should be triggered

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/DefaultEventSourceManager.java

If starting the event source throws a 404 error, this means that there
is no API endpoint to handle the resource on the server. This is
indicative of the associated CRD not being deployed yet. We therefore
need to handle this case to throw a MissingCRDException. Since we don't
have the needed CRD information at the point of the exception, we let
the exception trickle up and provide the information (crd name and
version) where we know about it.
Fixes #460

fix: improve missing CRD detection

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/DefaultEventSourceManager.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/IntegrationTestSupport.java
samples/pure-java/src/main/java/io/javaoperatorsdk/operator/sample/PureJavaApplicationRunner.java
samples/spring-boot-plain/src/main/java/io/javaoperatorsdk/operator/sample/Config.java

@metacosm @csviri This is a POC of the discussion we had on the weekly meeting about the lifecycle of controllers vs operator' start/stop method.
Fixes #488 
Fixes #489

feat: delay the registration of controller till the operator is started

---

operator-framework-core/pom.xml
operator-framework/pom.xml
operator-framework/src/test/java/io/javaoperatorsdk/operator/config/runtime/DefaultConfigurationServiceTest.java
operator-framework/src/test/resources/log4j2.xml
pom.xml
samples/common/pom.xml
samples/pom.xml
samples/pure-java/pom.xml
samples/spring-boot-plain/pom.xml

This PR aims to:
- move dependency management to the main pom
- use properties to define artifact versions
- explicitly set maven plugins version instead of rely on defaults (i.e. compiler plugin was 3.1, now 3.8.1)
- use log4j2 as the default logging impl and get rid of logback and sl4j-simple
Replaces #503

chore: refactor dependency management & settle on log4j2 as logging impl

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Metrics.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/AbstractControllerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ControllerConfigurationOverrider.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/Utils.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/ConfiguredController.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/DefaultEventHandler.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/EventDispatcher.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/ExecutionConsumer.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/ExecutionScope.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/PostExecutionControl.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/DefaultEventSourceManager.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventHandler.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventSourceManager.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/internal/CustomResourceEventSource.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/CustomResourceSelectorTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/DefaultEventHandlerTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/EventDispatcherTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/DefaultEventSourceManagerTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/internal/CustomResourceEventSourceTest.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/IntegrationTestSupport.java

The idea is to expand on the `ControllerRef` class to associate a controller with its configuration and propagate this entity instead of passing the controller, the configuration and very often the kube client to each object that needs that information. 
See commit message on https://github.com/java-operator-sdk/java-operator-sdk/commit/1c47ecf61f150bd241980ffff0c20afcfb003c57 for more details.
I've also taken the opportunity to clean up things from the Metrics class so that it's better decoupled from the business logic.
Fixes #496.

Introduce `ConfiguredController` concept, decouple Metrics code from business logic

---

.github/workflows/master-snapshot-release.yml
.github/workflows/pr.yml

We no longer need to use actions/cache.
Maven dependencies are cached via actions/setup-java
https://github.blog/changelog/2021-08-30-github-actions-setup-java-now-supports-dependency-caching/

chore(ci): drop actions/cache@v2

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/EventDispatcher.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/DefaultEventSourceManager.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/internal/CustomResourceEventSource.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/DefaultEventSourceManagerTest.java
pom.xml

Note that this relies on fabric8io/kubernetes-client#3492 so won't build
until this PR is merged and available in a release.
Fixes #552

fix: only throw MissingCRDException if we get a 404 on the target CRD

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/ConfiguredController.java

fix: make it clear that `ConfiguredController.init` should not be called

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/UpdateControl.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/DefaultEventHandler.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/EventDispatcher.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/PostExecutionControl.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/DefaultEventHandlerTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/EventDispatcherTest.java

Will update the examples after release.

Convinient API to re-schedule controller execution

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/ConfiguredController.java

Need this for v2 branch, but this might make sense to v1.*

EventSourceManager small fix

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/DefaultEventHandler.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/DefaultEventSourceManager.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/DefaultEventHandlerTest.java

DefaultEventHandler should not fire events if the handler is being closed

---

micrometer-support/pom.xml
micrometer-support/src/main/java/io/javaoperatorsdk/operator/micrometer/MicrometerMetrics.java
operator-framework-core/pom.xml
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Metrics.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/DefaultEventHandler.java
pom.xml

Fixes #576. This allows getting rid of mandatory micrometer dependency
if users are not interested in having metrics.

feat: extract micrometer support into its own module

---

samples/spring-boot-plain/src/main/java/io/javaoperatorsdk/operator/sample/Config.java

`Operator` does not have a `stop` method.
In accordance with the meaning, instead of the `stop` method, the `close` method was modified to operate as `destroyMethod `.

fix: use `close` as destroyMethod of Bean

---

docs/documentation/features.md
operator-framework-core/pom.xml
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/DefaultEventHandler.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/MDCUtils.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/internal/CustomResourceEventSource.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/TestUtils.java
operator-framework-core/src/test/resources/log4j2.xml

feat: contextual information about processing for loging using MDC

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/internal/TimerEventSource.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/internal/TimerEventSourceTest.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/event/EventSourceTestCustomResourceController.java

This periodic part in the `TimerEventSource` does not makes that much sense anymore, with the new API on update and delete controls. It makes more confusion imho than help.

fix!: remove periodic schedule from timer event source

---

operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/internal/CustomResourceSelectorTest.java
pom.xml

Note that this waits on https://github.com/fabric8io/kubernetes-client/pull/3562 at least to be able to solve the testing issue we've encountered since 5.9.0.

Prepare for upgrade to fabric8 5.10

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/OperatorTest.java

* Change deprecated kubernetesClient.getVersion to KubernetesClient.getKubernetesVersion
* Pass a non-null value as a parameter by creating defaultConfiguration in register(Reconciler reconciler)
* Remove unnecessary null defense code
by #687

[issue-687] Refactor/operator register api

---

README.md
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/ObservedGenerationAware.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/UpdateControl.java

fixes snapshot release on master: https://github.com/java-operator-sdk/java-operator-sdk/runs/4312545439?check_suite_focus=true

fix: build javadoc issue

---

README.md
docs/documentation/features.md
docs/documentation/getting-started.md
docs/documentation/use-samples.md
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/ErrorStatusHandler.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/EventSourceInitializer.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/RetryInfo.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/UpdateControl.java

Features chapter update for v2, added new sections.

Docs for v2

---

README.md

Update the example in the README.md file so that class names used in the Controller/Reconciler class are consistent with the class names used in the other example classes.
I noticed this inconsistency when trying out the java operator-sdk for the first time and found it confusing.
Signed-off-by: Katherine Stanley <11195226+katheris@users.noreply.github.com>

fix: Update examples in README to have consistent class names

---

README.md

Based on the other examples, the createOrUpdateResource function should reference the same class for both arguments, not two separate classes.
I noticed this inconsistency when trying out the java-operator-sdk for the first time and found it confusing.
Signed-off-by: Katherine Stanley <11195226+katheris@users.noreply.github.com>

fix: Update createOrUpdateResource example to reference correct class

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/Event.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/controller/ResourceEvent.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/sample/simple/TestCustomResource.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/sample/simple/TestCustomResourceV2.java

- fix: remove unneeded Kind annotation and add comment where it's needed
- fix: toString methods were incorrect

Minor fixes

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/Context.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/DefaultContext.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/informereventsource/InformerEventSourceTestCustomReconciler.java
sample-operators/tomcat-operator/src/main/java/io/javaoperatorsdk/operator/sample/TomcatReconciler.java
sample-operators/tomcat-operator/src/main/java/io/javaoperatorsdk/operator/sample/WebappReconciler.java

This PR should be reviewed first:
https://github.com/java-operator-sdk/java-operator-sdk/pull/775

Secondary resource access with Optional

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/DefaultContext.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/CachingEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/ResourceEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/controller/ControllerResourceEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerEventSource.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/CustomResourceSelectorTest.java

To make it consistent with other Optional APIs.

fix: Optional associated resource

---

.github/workflows/e2e-test-mysql.yml
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ControllerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/ErrorStatusHandler.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/EventSourceManagerTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcherTest.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/config/runtime/AccumulativeMappingWriter.java

- fix: e2e test name
- fix: missing javadoc
- fix: typo + javadoc
- fix: simplify assertion
- fix: avoid type masking

fix: minor fixes

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/ControllerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/controller/ControllerResourceEventSource.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/ResourceEventFilterTest.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/config/runtime/AnnotationConfiguration.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/CustomResourceFilterIT.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/customfilter/CustomFilteringTestReconciler.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/customfilter/CustomFilteringTestResource.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/customfilter/CustomFilteringTestResourceSpec.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/customfilter/CustomFlagFilter.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/customfilter/CustomFlagFilter2.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/retry/RetryTestCustomReconciler.java
sample-operators/tomcat-operator/src/main/java/io/javaoperatorsdk/operator/sample/CustomFilter.java
sample-operators/tomcat-operator/src/main/java/io/javaoperatorsdk/operator/sample/WebappReconciler.java

The behavior changed with this PR, if a resource event filtered out, we don't even add predicat.

fix with resource filter bug and related behavior update

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/Controller.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/ControllerTest.java

fix: only check for CRD if we're dealing with CustomResources

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/ReconcilerUtils.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/ReconcilerUtilsTest.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/config/runtime/AnnotationConfiguration.java

Also restores ReconcilerUtils.getDefaultReconcilerName(String)
Fixes #818

fix: ReconcilerUtils.isFinalizerValid should account for NO_FINALIZER

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/AbstractEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/retry/GenericRetryExecution.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcherTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/AbstractEventSourceTestBase.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/CachingEventSourceTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/CustomResourceSelectorTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/controller/ControllerResourceEventSourceTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/polling/PerResourcePollingEventSourceTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/polling/PollingEventSourceTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/timer/TimerEventSourceTest.java
operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/OperatorExtension.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/config/runtime/AccumulativeMappingWriter.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/config/runtime/ClassMappingProvider.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/config/runtime/ControllerConfigurationAnnotationProcessor.java

Few sonar reported issue fixes

Sonar reported issues

---

micrometer-support/src/main/java/io/javaoperatorsdk/operator/monitoring/micrometer/MicrometerMetrics.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventProcessor.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/EventProcessorTest.java

Refs: java-operator-sdk/java-operator-sdk#836

fix(micrometer): fix NPE when reconciling already marked events

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/ResourceID.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/Mappers.java

see: https://github.com/strimzi/kafka-access-operator/pull/2/files#r786855066
It is useful situations like this.

feature: add from first reference to ResourceID too

---

operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/OperatorExtension.java

> this fixes an issue with CRD registration
The underlying problem is that with a small/new cluster `etcd` takes some time to propagate the state.
Unfortunately I couldn't reproduce on my machine(any suggestion on how to reproduce is welcome!), but this should be a more "kubernetes-client" idiomatic way to obtain the same result. 🙂

More principled way to wait for the CRD

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/Ignore.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/Controller.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/DependentResourceManager.java

This allows downstream tools to safely ignore the annotated Reconciler
when considering which implementations to process.
Fixes #862

feat: add @Ignore annotation to mark internal Reconciler implementations

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventProcessor.java

It's can happen that after a custom resource deleted, event sources,
normally also informers still receive events about dependent resources deleted.

fix: change log level of no cr found

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/DefaultControllerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/DefaultResourceConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/KubernetesDependentResourceConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/KubernetesDependentResourceController.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerConfiguration.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/config/runtime/AnnotationConfiguration.java

- refactor: use DefaultResourceConfiguration for controller configuration
- feat: encapsulate Kubernetes dependent configuration

refactor: clean up configurations

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ControllerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/DefaultControllerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/DefaultResourceConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/DependentResourceConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/DependentResourceController.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/DependentResourceControllerFactory.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/KubernetesDependentResourceConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/KubernetesDependentResourceController.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/DependentResourceManager.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerConfiguration.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/config/runtime/AnnotationConfiguration.java

- fix: do not call default resource class resolution logic by default
- fix: do not create DependentResources directly from configuration

fix: decouple DependentResource creation from configuration

---

.github/workflows/sonar.yml

This prevents the Sonar check to run on the forks (will be marked as "Skipped") instead of failing.

Disable Sonar check on forks

---

docs/documentation/features.md
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/ObservedGenerationAware.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/controller/ResourceEventFilters.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/ResourceEventFilterTest.java

From now on on startup we always reconcile the resources. Since deletes cannot be detected automatically, thus if a resource deletion happens while de operator is down, it won't trigger a reconciliation on startup. So this is important for correctness in general.

feat: remove feature of filter event with observed generation

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/Controller.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/config/runtime/AnnotationConfiguration.java

fix: fail explicitly if current namespace is requested but not available

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/KubernetesDependent.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ResourceConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/Controller.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerConfiguration.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/config/runtime/AnnotationConfiguration.java

- fix: fail explicitly if current namespace is requested but not available
- fix: retain annotation for reflective access
Fixes #897

fix: NPE when no namespace is provided in kube config

---

.github/workflows/pr.yml

- separated check format and unit tests from the matrix build with kubernetes/Java versions
- excluded all but the first and last kubernetes version for Java 11 (keeping Java 17 for coverage)
As a "Free" GH Actions account we have 20 concurrent jobs and we are already pretty much flooding them up.
I do believe that this setup is not compromising test coverage.
This proposed setup is biased toward Java 17, open to swap it with Java 11 on request.

Faster CI feedback loop

---

docs/documentation/use-samples.md

When querying Maven central using the artifactId `operator-framework`, there were multiple matches:
- One using the groupId: `com.github.containersolutions`
- Another one using: `io.javaoperatorsdk`
While is obvious that the right one is the one using the groupId `io.javaoperatorsdk`, we can avoid confusions by querying Maven central using both the artifactId and the group Id fields.

Add groupId in Maven query

---

sample-operators/webpage/README.md

k8s/crd.yml no longer exists as the CRDs for Samples
are automatically generated by the fabric8 maven plugin.
I've aligned to:
https://github.com/java-operator-sdk/java-operator-sdk/blob/main/sample-operators/tomcat-operator/README.md?plain=1#L40-L45

fix README instructions for webpage sample

---

operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/InClusterCurl.java
sample-operators/tomcat-operator/src/test/java/io/javaoperatorsdk/operator/sample/TomcatOperatorE2E.java

Moving the code for running curl in cluster to it's own utility class as it's a really useful thing to have.

Utility around curl in Cluster

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/AbstractDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/Matcher.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/Updater.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/GenericKubernetesResourceMatcher.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResource.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/GenericKubernetesResourceMatcherTest.java
sample-operators/mysql-schema/src/main/java/io/javaoperatorsdk/operator/sample/dependent/SecretDependentResource.java

feat: matcher avoiding creating the desired state when possible

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventSourceManager.java

fix: state controller name in exception

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/AnnotationControllerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/BaseConfigurationService.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/config/runtime/AnnotationControllerConfiguration.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/config/runtime/DefaultConfigurationService.java

feat: add non-apt-tied behavior annotation and configuration to core

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/informer/InformerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/PrimaryToSecondaryMapper.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/SecondaryToPrimaryMapper.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/Mappers.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerEventSourceTest.java
sample-operators/mysql-schema/src/main/java/io/javaoperatorsdk/operator/sample/dependent/SecretDependentResource.java
sample-operators/tomcat-operator/src/main/java/io/javaoperatorsdk/operator/sample/WebappReconciler.java
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageReconcilerDependentResources.java

@metacosm what do you think about this renaming. Not sure how much actual backwards compatibiilty issues it will make since usually implemented as lambda function. But we can document these minor changes.
The current names are very obscure for me, have to think about every time I check.
Also would add `glossary` page to the web page docs, to cleary define:
- Secondary Resource (what is a resource actually controller creates)
- Dependent Resource (is the dependent resource feature)
If you agree. 
Later we can extend glossary with additional notions.

fix: renaming mapper primary <-> secondary

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/AnnotationControllerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ControllerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ControllerConfigurationOverrider.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/DefaultControllerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/dependent/DependentResourceSpec.java

refactor: getDependentResources return type is more generic

---

operator-framework/src/test/java/io/javaoperatorsdk/operator/SubResourceUpdateIT.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/subresource/SubResourceTestCustomReconciler.java

A not very elegant fix for this integration test, that fails some times:
`SubResourceUpdateIT.updateCustomResourceAfterSubResourceChange:89`
https://github.com/java-operator-sdk/java-operator-sdk/runs/5512866209?check_suite_focus=true

fix: flaky integration test

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/AbstractDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/DependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/ReconcileResult.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/external/AbstractSimpleDependentResource.java

This PR is about proposing an more info about reconciliation (currently for standalone mode). And also a discussion starter for the topic :)
see also: https://github.com/java-operator-sdk/java-operator-sdk/issues/957

Reconcile api proposal

---

docs/_data/sidebar.yml
docs/documentation/dependent-resources.md

for just created branch and a skeleton (well a very skinny one), to start on the docs for dependent resources. 
Will continue expanding this.

docs: dependent resources

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/DefaultContext.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/EventSourceInitializer.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/UpdateControl.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/DependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/EventSourceProvider.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/Controller.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/ResourceOwner.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/AbstractDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/AbstractEventSourceHolderDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/external/AbstractCachingDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/external/AbstractSimpleDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/external/PerResourcePollingDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/external/PollingDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventSourceManager.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventSources.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/AbstractResourceEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/CachingEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/ResourceEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/controller/ControllerResourceEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/ManagedInformerEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/polling/PerResourcePollingEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/polling/PollingEventSource.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/UtilsTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/external/AbstractSimpleDependentResourceTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/EventSourceManagerTest.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/standalonedependent/StandaloneDependentTestReconciler.java
sample-operators/mysql-schema/src/main/java/io/javaoperatorsdk/operator/sample/dependent/SecretDependentResource.java
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageStandaloneDependentsReconciler.java

The benefit of this change is multi-fold:
- simplifies AbstractDependentResource which doesn't have to handle
cases it should not be concerned about
- allows to share more code with AbstractSimpleDependentResource
- enforces that the same name is used for the DependentResource and
EventSource even in the standalone mode when using one of the provided
implementations

feat: add a DependentResource implementation that's also an EventSource

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/DefaultContext.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/ResourceOwner.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/AbstractDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/external/AbstractCachingDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/external/AbstractSimpleDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/CachingEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/controller/ControllerResourceEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/ManagedInformerEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/polling/PerResourcePollingEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/polling/PollingEventSource.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/UtilsTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/external/AbstractSimpleDependentResourceTest.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/standalonedependent/StandaloneDependentTestReconciler.java
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageStandaloneDependentsReconciler.java

`getResource` is either called on event source or dependent resource. In both context it should be obivius from `getResource` that it is about the resource dependent resource / or event source is managing / caching.

fix: rename getAssiciatedResource to getSecondaryResource

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/external/AbstractCachingDependentResource.java

It does not make sense to get the resource from the cache, basically that is what we want to avoid.

fix: abstract fetch resource

---

sample-operators/mysql-schema/src/main/java/io/javaoperatorsdk/operator/sample/MySQLSchemaReconciler.java

I guess branch next has been merged into main.
mysql-schema sample was retrieving a secondary resource by the primary type. I think it should have fail but it doesn't not.
That is `context.getSecondaryResource(Primary.class)` actually returns something.  Shoud I raise an issue  ?

fix(mysql-schema): use proper secondary resource type

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/DefaultContext.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/EventSourceInitializer.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventSourceManager.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventSources.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/EventSource.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/reconciler/EventSourceInitializerTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/EventSourceManagerTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/EventSourcesTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/EventSourceTest.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/createupdateeventfilter/CreateUpdateEventFilterTestReconciler.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/informereventsource/InformerEventSourceTestCustomReconciler.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/standalonedependent/StandaloneDependentTestReconciler.java
sample-operators/mysql-schema/src/main/java/io/javaoperatorsdk/operator/sample/MySQLSchemaReconciler.java
sample-operators/tomcat-operator/src/main/java/io/javaoperatorsdk/operator/sample/WebappReconciler.java
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageReconciler.java
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageStandaloneDependentsReconciler.java

- Event sources not need to start in particular order this is handled by the processor - it starts after event sources started
- If asked for a secondary resource from the context for a event source using the name, throws exception if event source not present with that name

fix: event sources no ordered start & missing event source throws exception

---

docs/documentation/dependent-resources.md
operator-framework/src/test/java/io/javaoperatorsdk/operator/OrderedManagedDependentIT.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/orderedmanageddependent/ConfigMapDependentResource1.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/orderedmanageddependent/ConfigMapDependentResource2.java

The problem was that there were two informers without label selector for the 2 config maps, so event filtering was not working properly. There are 2 solutions in this case, share the event source between the dependents or use label selectors.

fix: Ordered Managed Dependent IT and filtering

---

.github/workflows/snapshot-releases.yml
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/ReconcilerUtils.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/Controller.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventSourceManager.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/controller/ControllerResourceEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/timer/TimerEventSource.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/MockKubernetesClient.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/ReconcilerUtilsTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/ControllerTest.java
sample-operators/mysql-schema/src/main/java/io/javaoperatorsdk/operator/sample/MySQLSchemaReconciler.java

- fix: start timer as daemon to avoid prolonging the app's life
- fix: exit operator on exception when starting

fix: shut down operator when failing to start

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/UpdateControl.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcher.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcherTest.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/ControllerExecutionIT.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/simple/TestReconciler.java

Ability to patch resource and status using `UpdateControl`.

feat: patching with update control

---

sample-operators/webpage/README.md
sample-operators/webpage/k8s/webpage.yaml

The webpage sample does not work OOTB with the `k8s/webpage.yaml`, as the default reconciler watches for webpage resources without labels.

fix: make webpage sample work OOTB

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/AnnotationControllerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ControllerConfigurationOverrider.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/DefaultResourceConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ResourceConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/Constants.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/ControllerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependent.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResourceConfig.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/OperatorTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/ControllerConfigurationOverriderTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/MockControllerConfiguration.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/ResourceConfigurationTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/ControllerTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/EventSourceManagerTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcherTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerEventSourceTest.java

This uses the constant that was initially introduced for the same reason
on KubernetesDependent, which is now moved to Constants. Uncovered
several issues with configuration overriding in the process and added
test coverage.
Fixes #1176

feat: make default watched namespaces behavior explicit

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/AggregatedOperatorException.java

Overriding `toString`. Adding the first exception as cause - maybe would be better to override `printStackTrace` to handle the causes? Respectively `getOurStackTrace` in `Throwable` to have it nicer?

aggregate exception improvement

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/OperatorTest.java
operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/OperatorExtension.java

Controllers should not be exposed, those are internal structures for now. Without a clear purpose this can be confusing.

fix: remove get controllers from operator

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/RegisteredController.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/Controller.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/OperatorTest.java

Allows to retrieve information from registered controllers from
Operator, in particular if there are any registered controllers, which
the Quarkus extension uses to determine whether or not to start the
Operator.

feat: make RegisteredController a little more useful

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/AnnotationControllerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ControllerConfigurationOverrider.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/DefaultResourceConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/NamespaceChangeable.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ResourceConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/informer/InformerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/Constants.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependent.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResourceConfig.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/MockControllerConfiguration.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerEventSourceTest.java

- refactor!: move SAME_AS_CONTROLLER constant to Constants class, add set
- refactor!: rename WATCH_CURRENT_NAMESPACE_SET to match other constants

refactor: clean namespaces constants

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/PostExecutionControl.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcher.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcherTest.java

Fix for the following error happens in some cases.
The cause was, that if there are event sources registered and a new resource is created, the finalizer was added, but is was not cached in tempCache, so if an event source produced an event just after, but before the update event from finalizer add arrived, the reconciliation used the resource from the cache without the finalizer (the first version), so controller tried to add the finalizer again.
The fix is actually trivial, just caching the resource to tempCache, as we do at any other update (not patch) operation.
```
job-example', namespace='default'}
2022-05-26 22:51:04,117 "48" i.j.o.p.e.EventProcessor       [DEBUG] [default.basic-session-cluster.36958] Skipping executing controller for resource id: …
```

fix: resource cache after finalizer add

---

operator-framework/src/test/java/io/javaoperatorsdk/operator/MultipleDependentResourceIT.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/multipledependentresource/MultipleDependentResourceConfigMap.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/multipledependentresource/MultipleDependentResourceCustomResource.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/multipledependentresource/MultipleDependentResourceReconciler.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/multipledependentresource/MultipleDependentResourceStatus.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/multiplesecondaryeventsource/MultipleSecondaryEventSourceCustomResource.java

An IT that shows multiple dependent resources of the same type.
Based on a discussion on Discord with @csviri .

Multiple dependent resource integration test

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/AbstractDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/AbstractEventSourceHolderDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/external/AbstractCachingDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/external/AbstractPollingDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/external/AbstractSimpleDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/external/PerResourcePollingDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/external/PollingDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/CRUDKubernetesDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/CRUKubernetesDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResource.java

The goal is to allow downstream processes (e.g. the Quarkus extension)
which might need to introspect only user-defined DependentResource
implementations, similarly to what was done for Reconciler
implementations already.

chore: add @Ignore to internal/intermediate DependentResources

---

docs/documentation/use-samples.md

Adding config required for SpringBoot docs

---

operator-framework/src/main/java/io/javaoperatorsdk/operator/config/runtime/ControllerConfigurationAnnotationProcessor.java

Using a fixed version works ok-ish, till you upgrade your jdk version. Then annoying warnings start creeping into the build.
This is a more permanent solution.

chore: apt processors now suggests the latest version

---

operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/CustomResourceSelectorTest.java
pom.xml

This PR updates okhttp to newer version, in order to fix the security issue mentioned here:
https://github.com/fabric8io/kubernetes-client/issues/4290

feat: update to okhttp4

---

README.md

feat: add section highlighting JOSDK users

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/AbstractConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/BaseConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverrider.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/StandaloneDependentResourceIT.java

The json mapper might be fine tuned for application in some cases, probably in the default case we should use that everywhere if possible.
see also: https://github.com/fabric8io/kubernetes-client/issues/1308

feat: use fabric8 client json mapper by default

---

README.md

Add the Keycloak operator

---

.github/workflows/pr.yml
operator-framework-bom/pom.xml
pom.xml

When a project has multiple modules, publishing a bom is considered to be a good practice for users to more easily manage dependencies. For example: https://search.maven.org/artifact/io.fabric8/kubernetes-client-bom and https://search.maven.org/artifact/io.micrometer/micrometer-bom.
I'm not sure of the actual artifact deployment process, so hopefully this makes sense.
I tested locally and it works.

Add bom module

---

operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/polling/PollingEventSourceTest.java

see also discussion here: https://discord.com/channels/723455000604573736/780769121305493544/1011181916722049124

feat: add additional test for `PollingEventSource`

---

docs/documentation/dependent-resources.md
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/Matcher.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/GenericKubernetesResourceMatcher.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/GenericKubernetesResourceMatcherTest.java

feat: make it possible to also check annotations/labels when matching

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverrider.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceProvider.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/OperatorTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverriderTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceProviderTest.java
sample-operators/leader-election/src/test/java/io/javaoperatorsdk/operator/sample/LeaderElectionE2E.java

- fix: make it easier to support new field when overriding configuration
- refactor: simplify constructors chaining

fix: improve ConfigurationServiceOverrider's resilience

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/inbound/CachingInboundEventSource.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/inbound/CachingInboundEventSourceTest.java

Refs: https://github.com/java-operator-sdk/java-operator-sdk/issues/1424
Signature change but I doubt anyone use this event source as it is not currently working well.
Expiration needs a single fetcher by secondary, So I prefered seperating the behavior in a another event source as not everyone will need this.

feat: add resource fetcher to CachingInboundEventSource

---

docs/documentation/features.md

The link points to a non-existing commit, and `LeaderElectionConfigurationBuilder` does not exist.

Fix link to LeaderElection test

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverrider.java

Fixes a bug that if only the number overwrite did not end up with correct executor service.

fix: config service override executor service concurrent reconciliation numbers

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/LeaderElectionManager.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/LeaderElectionConfiguration.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/LeaderElectionManagerTest.java
sample-operators/leader-election/k8s/namespace-inferred-operator-instance-2.yaml
sample-operators/leader-election/k8s/namespace-inferred-operator.yaml
sample-operators/leader-election/pom.xml
sample-operators/leader-election/src/main/java/io/javaoperatorsdk/operator/sample/LeaderElectionTestOperator.java
sample-operators/leader-election/src/test/java/io/javaoperatorsdk/operator/sample/LeaderElectionE2E.java

This PR makes providing lease namespace optional. If unspecified, it will try to read from a file pointed by system property or env var `kubenamespace` with default value as `/var/run/secrets/kubernetes.io/serviceaccount/namespace` which is injected by k8s. The code is inspired by https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java.
The idea is to simplify use code because in most cases users will need to do the same. Please let me know if this makes sense. Thanks.
@csviri @metacosm

Try to get lease namespace if unspecified

---

operator-framework-core/src/test/java/io/javaoperatorsdk/operator/LeaderElectionManagerTest.java

this test would fail for anyone that has kube config inited locally that makes is quite problematic, would rather remove it

fix: remove problematic leader election unit test

---

.github/workflows/e2e-test.yml
.github/workflows/pr.yml
.github/workflows/sonar.yml
adr/001-Introducing-ADRs.md
operator-framework/src/test/java/io/javaoperatorsdk/operator/MultiVersionCRDIT.java

In this PR we introduce ADRs. And should agree on the format. So traditionally first ADR is an ADR about ADRs :)
Closes #1272

docs: introduce ADRs

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverrider.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/InformerStoppedHandler.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerWrapper.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/MockKubernetesClient.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverriderTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerEventSourceTest.java
operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/AbstractOperatorExtension.java
operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/ClusterDeployedOperatorExtension.java
operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/LocallyRunOperatorExtension.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/MultiVersionCRDIT.java
pom.xml

Requires https://github.com/fabric8io/kubernetes-client/pull/4412
- chore: update to SNAPSHOT version of fabric8 client
- feat: enable configuring a handler to listen to informers stopping

feat: enable configuring a handler to listen to informers stopping

---

adr/002-Custom-Resource-Deserialization-Problem.md

Created an ADR for this quesiton. So we are all aligned. 
(Feel free to improve the content and/or wording)

docs: adr regarding the cr deserialization problem

---

sample-operators/leader-election/pom.xml
sample-operators/mysql-schema/pom.xml
sample-operators/tomcat-operator/pom.xml
sample-operators/webpage/pom.xml

refactor: use bom in samples

---

operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/AbstractOperatorExtension.java
operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/ClusterDeployedOperatorExtension.java
operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/LocallyRunOperatorExtension.java

We are using the Testcontainers K3s-module (https://www.testcontainers.org/modules/k3s/) for integration tests while working on our operators.
These k8s-instances are created on the fly at test-runtime there is never a KUBECONFIG-env or something in ~/.kube/config which means that they can't be used with the default test-implementatio which uses `new KubernetesClientBuilder().build()`and relies on the existence of either of the two.
I added the ability to inject your own instanc eof a KubernetesClient to the builders for LocallyRunOperatorExtension and ClusterDeployedOperatorExtension. 
In case none is provided it falls back to the old behaviour.
I hope this helps, feel free to leave comments for things I should change/add :)
Thanks a lot for your great work!

Add ability to provide a preconfigured KubernetesClient

---

.github/workflows/release.yml

This fixes the release so it won't fail after a successful actual release of artifacts:
https://github.com/java-operator-sdk/java-operator-sdk/actions/runs/3282025485
we can properly refactor later.

fix: remove unnecessary release step

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java

I think we should have here system exit by default.
cc @andreaTP @vmuzikar

feat: add default stop handler

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/AnnotationControllerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverrider.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ControllerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ControllerConfigurationOverrider.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/DefaultControllerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ResourceConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/CacheSyncTimeout.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/ControllerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventSourceManager.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerManager.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerWrapper.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/ManagedInformerEventSource.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/ControllerManagerTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcherTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/ResourceEventFilterTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/controller/ControllerResourceEventSourceTest.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/InformerRelatedBehaviorITS.java

this makes sense if there are multiple controlelrs, where this value might vary

feat: moving cache sync timeout to controller level

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/ReconcilerUtils.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/ReconcilerUtilsTest.java

fix: fix setSpec NoSuchMethodException for custom resource (#1589)

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/InformerRelatedBehaviorITS.java
sample-operators/leader-election/src/main/java/io/javaoperatorsdk/operator/sample/LeaderElectionTestOperator.java
sample-operators/mysql-schema/src/main/java/io/javaoperatorsdk/operator/sample/MySQLSchemaOperator.java
sample-operators/tomcat-operator/src/main/java/io/javaoperatorsdk/operator/sample/TomcatOperator.java
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageOperator.java

The graceful shutdown does not help. We should remove this. Users can directly add shutdown hooks anyway if needed just with plain Java API.

fix: deprecate install webhook

---

docs/documentation/features.md
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/RegisteredController.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/RuntimeInfo.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/health/ControllerHealthInfo.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/health/EventSourceHealthIndicator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/health/InformerEventSourceHealthIndicator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/health/InformerHealthIndicator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/health/InformerWrappingEventSourceHealthIndicator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/health/Status.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/Controller.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventSourceManager.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventSources.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/EventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerManager.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerWrapper.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/ManagedInformerEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/polling/PerResourcePollingEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/polling/PollingEventSource.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/polling/PollingEventSourceTest.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/InformerRelatedBehaviorITS.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/informerrelatedbehavior/InformerRelatedBehaviorTestReconciler.java
sample-operators/webpage/k8s/operator.yaml
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/LivenessHandler.java
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/StartupHandler.java
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageOperator.java

Expose runtime information mainly about event sources and informers so that can be used to create custom / tailored liveness probes.

feat: runtime info for health probes

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerManager.java
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageOperator.java

alternative to:
https://github.com/java-operator-sdk/java-operator-sdk/pull/1615
This might be a better solution since, will stop the leader elector if somebody explicitly calls stop

fix: leader election stop deadlock

---

README.md

I have developed some projects based on JOSDK and would like to share them with the community in the hope that they can provide some help.
* [Strimzi Schema Registry Operator](https://github.com/shangyuantech/strimzi-registry-ksql-operator)
* [Airflow Dag Operator](https://github.com/cdmikechen/airflow-dag-operator)

Add more JOSDK use cases

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/OperatorTest.java

If you create an Operator instance without using the `overrider` to set the leader election config, the configuration singleton is set twice leading to a ISE. 
The method `LeaderElectionManager#init` relies on the singleton config but the config is not set yet at that moment.
Note that I found out this issue by using [Quarkus Operator SDK 5.0.2.Beta](https://github.com/quarkiverse/quarkus-operator-sdk)

fix: leader election manager init when not using config overrider

---

docs/documentation/use-samples.md

Including spring-boot-plain. Check https://github.com/java-operator-sdk/java-operator-sdk/pull/1384.

#1384, smoke test samples were removed.

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/DependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/Controller.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/AbstractDependentResourceNode.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/AbstractWorkflowExecutor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/DefaultDependentResourceNode.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/DefaultManagedWorkflow.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/DependentResourceNode.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/ManagedWorkflow.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/ManagedWorkflowFactory.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/ManagedWorkflowSupport.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/NodeExecutor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/SpecDependentResourceNode.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/Workflow.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowBuilder.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowCleanupExecutor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowReconcileExecutor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/builder/WorkflowBuilder.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/AbstractWorkflowExecutorTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/ManagedWorkflowSupportTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/ManagedWorkflowTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/ManagedWorkflowTestUtils.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowCleanupExecutorTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowReconcileExecutorTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowTest.java
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageDependentsWorkflowReconciler.java

This allows for the workflow graph to be resolved at build time from a 
factory, the dependent resources being configured as needed at runtime
via the resolve mechanism.

feat: workflows can be created without associated dependent resource

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcher.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcherTest.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/CachePruneIT.java

This reverts commit c72baa2ee19c3e2a8a8d6cb2cb39ca5f0f0e7522.

Revert "chore: temporarily revert SSA for finalizers (#1654)"

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/dependent/DependentResourceConfigurationResolver.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/ControllerConfigurationOverriderTest.java

This fixes an issue with unit tests where order matters. But state state should be avoided in the future, also this refactored.

fix: non-independent unit tests because static state

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResource.java

This fixes issue #1682, see issue for details.

fix: don't require namespace in KubernetesDependentResource.prepare()

---

operator-framework-core/pom.xml
operator-framework-core/src/main/java-templates/io/javaoperatorsdk/operator/Versions.java
operator-framework-core/src/main/java-templates/io/javaoperatorsdk/operator/api/config/Versions.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/Utils.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/Version.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/VersionTest.java

- Generate a Versions file to be consumed at runtime
- review comments
- add a test for the version
- refactor: consolidate access to versions

feat: provide Kubernetes client version

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/MDCUtils.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/AbstractDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventProcessor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/Mappers.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/externalstate/ExternalStateReconciler.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/externalstate/ExternalWithStateDependentResource.java
sample-operators/mysql-schema/src/main/java/io/javaoperatorsdk/operator/sample/dependent/SchemaDependentResource.java

fix: avoid computing potentially unused values

---

README.md

Hi folks,
We now used the JOSDK for the last 6 months in our Kotlin based project.
Thank you for the hard work and hopefully our Kotlin based usage of the JOSDK is a good starting point for others interested in using the JOSDK in a Kotlin based project.
Link to our project: https://github.com/glasskube/operator

docs: add Glasskube reference implementation

---

docs/documentation/features.md
micrometer-support/pom.xml
micrometer-support/src/main/java/io/javaoperatorsdk/operator/monitoring/micrometer/MicrometerMetrics.java
micrometer-support/src/test/java/io/javaoperatorsdk/operator/monitoring/micrometer/MetricsCleaningOnDeleteIT.java

feat: remove CR meters when they are deleted (after a delay)

---

operator-framework/src/test/java/io/javaoperatorsdk/operator/PrimaryToSecondaryIT.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/PrimaryToSecondaryMissingIT.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/primarytosecondary/JobReconciler.java

The goal is this PR is to show why primary to secondary mapper is needed, serves to showcase the problematic use case.

feat: add sample to primary to secondary missing issue

---

.github/workflows/integration-tests.yml
.github/workflows/pr.yml
operator-framework/pom.xml
pom.xml

feat: parameterize http client implementation in ITs

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/AbstractWorkflowExecutor.java

Making this future proof, even if now not strictly required.

improve: workflows impl detail future proof

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ResolvedControllerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/DependentResourceWithExplicitState.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/GenericKubernetesResourceMatcher.java

Fixes problem that prevent build of next and snapshot release.

docs: fix javadoc issues

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/AbstractConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/BaseConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverrider.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ExecutorServiceManager.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/Utils.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverriderTest.java

fix: enforce valid values when creating ExecutorServices

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/GenericKubernetesResourceMatcher.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/ResourceUpdatePreProcessor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/processors/ClusterRoleBindingResourceUpdatePreProcessor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/processors/ClusterRoleResourceUpdatePreProcessor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/processors/ConfigMapResourceUpdatePreProcessor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/processors/GenericResourceUpdatePreProcessor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/processors/RoleBindingResourceUpdatePreProcessor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/processors/RoleResourceUpdatePreProcessor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/processors/SecretResourceUpdatePreProcessor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/processors/ServiceAccountResourceUpdateProcessor.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/GenericKubernetesResourceMatcherTest.java

- feat: use processors for matching as well since usually both are related
- refactor: remove unneeded parameter that can also be inferred from DR

feat: use processors for matching as well since usually both are related

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/processors/GenericResourceUpdatePreProcessor.java

fix: IllegalStateException observed with Role due to wrong import

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/ResourceUpdatePreProcessor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/processors/GenericResourceUpdatePreProcessor.java

- fix: clean-up unneeded matcher field
- fix: restore backwards compatibility

fix: restore backwards compatibility

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/LeaderElectionManager.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/AbstractConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/BaseConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverrider.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ResourceConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/GenericKubernetesResourceMatcher.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/ResourceUpdatePreProcessor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcher.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/processors/ClusterRoleBindingResourceUpdatePreProcessor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/processors/ClusterRoleResourceUpdatePreProcessor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/processors/ConfigMapResourceUpdatePreProcessor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/processors/RoleBindingResourceUpdatePreProcessor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/processors/RoleResourceUpdatePreProcessor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/processors/SecretResourceUpdatePreProcessor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/processors/ServiceAccountResourceUpdateProcessor.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/LeaderElectionManagerTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/MockKubernetesClient.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverriderTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/GenericKubernetesResourceMatcherTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/GenericResourceUpdatePreProcessorTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcherTest.java
operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/AbstractOperatorExtension.java
operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/LocallyRunOperatorExtension.java
pom.xml
sample-operators/mysql-schema/src/main/java/io/javaoperatorsdk/operator/sample/MySQLSchemaOperator.java
sample-operators/tomcat-operator/src/main/java/io/javaoperatorsdk/operator/sample/TomcatOperator.java

feat: decouple from ObjectMapper

---

docs/documentation/dependent-resources.md

Fix the first link and update the following.

Fix a few links

---

docs/documentation/contributing.md
docs/documentation/features.md
docs/documentation/workflows.md

Hey hello there,
I'm new to the java-operator-sdk , was browsing the documentation and found some small typos. So just opened this PR. 
Thanks for this awesome operator :)

docs: fix small typos

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/CustomResourceUtils.java

<fix>: fix #1981

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/AbstractDependentResource.java

In case of Secrets this migh log sensitice data.

fix: logging whole resource just on trace level

---

sample-operators/webpage/k8s/operator.yaml

Although operator.yaml is mostly used by the E2E test, it would be nice to have it available for manual tests as well
Manually applying would currently result in the following error:
```
kubectl apply -f k8s/operator.yaml
serviceaccount/webpage-operator unchanged
..
...
The ClusterRoleBinding "operator-admin" is invalid: subjects[0].namespace: Required value
```

feat: update ClusterRoleBinding with default namespace ( WebPage sample )

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/DefaultWorkflow.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowTest.java

There is no point for a workflow builder with zero size toplevel resources ( A bit illogically  ).
The following builder is very strange , but it demonstrates how wrong Workflow configuration could lead for a deadlock state (topLevelResources.size() == 0, cycle detection still does not implemented )
```
initDependentResources(kubernetesClient);
workflow = new WorkflowBuilder<WebPage>()
.addDependentResource(configMapDR)
.addDependentResource(deploymentDR).dependsOn(configMapDR)
.addDependentResource(serviceDR).dependsOn(deploymentDR)
.addDependentResource(ingressDR).dependsOn(serviceDR)
.addDependentResource(configMapDR).dependsOn(serviceDR)
.build();
```
For cases where the initializations aren't logical, this exception throw can comes in
Hope is following the guidelines and the project …

fix: standalone workflows now fail on top-level cycles

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/LoggingUtils.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcher.java

see: https://github.com/operator-framework/java-operator-sdk/discussions/1983

fix: do not log sensitive resources

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerEventSource.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/DependentReInitializationIT.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/dependentreinitialization/ConfigMapDependentResource.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/dependentreinitialization/DependentReInitializationCustomResource.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/dependentreinitialization/DependentReInitializationReconciler.java

improve: dependent resource can be re-initialized

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventProcessor.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/EventProcessorTest.java

if leader election not running delete event was not cleaning up state

fix: processor issue with cleanup resources

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/GenericKubernetesResourceMatcher.java

Just a small improvement to re-use the `ignoreList` from line 178 instead of creating the identical `ignoreList` again in line 208.
Also optimized two `if (!method()) return false;` to `return method();` (suggestion from IDEA).

Re-use ignoreList in GenericKubernetesResourceMatcher

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/Context.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/DefaultContext.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/IndexedResourceCache.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/ResourceCache.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/IndexedResourceCache.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/IndexerResourceCache.java

feat: make primary cache accessible from Context

---

sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/dependentresource/ConfigMapDependentResource.java
sample-operators/webpage/src/test/java/io/javaoperatorsdk/operator/sample/WebPageOperatorAbstractTest.java

This might be confusing and should not be there, and update should not be used here.

fix: remove pod delete web page dependent test

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverrider.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/informer/InformerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/controller/ControllerResourceEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/ManagedInformerEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/TemporaryResourceCache.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerEventSourceTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/informer/TemporaryResourceCacheTest.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/CreateUpdateInformerEventSourceEventFilterIT.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/PreviousAnnotationDisabledIT.java

provides two options
- to control if the annotation is used (to omit events that come too quickly)
- to parse the resource version (to keep the cache up-to-date and omit events if they come too slowly)
Looking for feedback on if these are the right places to introduce the configuration.

eventing refinements mentioned on #2012

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/SecondaryToPrimaryMapper.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/DependentCustomMappingAnnotationIT.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/dependentcustommappingannotation/CustomMappingConfigMapDependentResource.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/dependentcustommappingannotation/DependentCustomMappingCustomResource.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/dependentcustommappingannotation/DependentCustomMappingReconciler.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/dependentcustommappingannotation/DependentCustomMappingSpec.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/primaryindexer/DependentPrimaryIndexerTestReconciler.java
sample-operators/mysql-schema/src/main/java/io/javaoperatorsdk/operator/sample/dependent/SecretDependentResource.java

The implementation does not model very nicely the situation but makes it doable relatively easily.

feat: customize mapping annotation in kubernetes dependent resource

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerEventSource.java
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageReconciler.java
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/dependentresource/ConfigMapDependentResource.java

This mean to be reverted after found the issue.

add logging to help identify issue with failing e2e test

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerEventSource.java
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageReconciler.java
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/dependentresource/ConfigMapDependentResource.java

This reverts commit 1e5e03e5094ea84234c45119514bf45e05043bbc

revert: "add logging to help identify issue with failing e2e test "

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/AbstractDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/AbstractExternalDependentResource.java

improve: make sure there is no infinite recursion by default for external service

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ControllerConfigurationOverrider.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/ControllerConfigurationOverriderTest.java

fix: preserve the original itemstore

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowReconcileExecutor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventSourceManager.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventSourceRetriever.java

improve: api for dynamic registration of event sources

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverrider.java

This PR is a follow-up to #2166.
The idea here is to modify `ConfigurationServiceOverrider` to accept implementations of `DependentResourceFactory`. This modification can then be utilized by [OperatorAutoConfiguration](https://github.com/operator-framework/josdk-spring-boot-starter/blob/2ccd8556f836586d9c4d5bfbdccb6610da0f280f/starter/src/main/java/io/javaoperatorsdk/operator/springboot/starter/OperatorAutoConfiguration.java#L123) in [josdk-spring-boot-starte](https://github.com/operator-framework/josdk-spring-boot-starter/tree/main) to inject a Spring-aware `DependentResourceFactory`.
**Note**: I made this change with a high-level understanding of the codebase. I am open to learning and adjusting the changes based on suggestions if they do not align with the future plans of the library.

feat: Made ConfigurationServiceOverrider to accept dependent resource factory

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/EventSourceInitializer.java
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageOperator.java
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageReconciler.java
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageStandaloneDependentsReconciler.java
sample-operators/webpage/src/test/java/io/javaoperatorsdk/operator/sample/WebPageOperatorStandaloneDependentResourcesE2E.java

also change webpage sample use workflow builder

feat: extending event source context with workflow support

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventSourceManager.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventSourceRetriever.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/controller/ControllerResourceEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/ManagedInformerEventSource.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/DynamicGenericEventSourceRegistrationIT.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/dynamicgenericeventsourceregistration/DynamicGenericEventSourceRegistrationCustomResource.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/dynamicgenericeventsourceregistration/DynamicGenericEventSourceRegistrationReconciler.java

this will allow to multiple threads wait idempotently for the start of an informer event source

improve: thread-safe idempotent dynamic informer event source start

---

bootstrapper-maven-plugin/pom.xml

fixes also missing goal prefix, see: https://maven.apache.org/guides/introduction/introduction-to-plugin-prefix-mapping.html

chore: bootstrapper maven-plugin-plugin version

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/DependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/AbstractDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/AbstractEventSourceHolderDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/AbstractWorkflowExecutor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/DefaultManagedWorkflow.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/DefaultWorkflow.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/DependentResourceNode.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowBuilder.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/ControllerConfigurationOverriderTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/dependent/DependentResourceConfigurationResolverTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/AbstractWorkflowExecutorTest.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/config/BaseConfigurationServiceTest.java

keep name on DR node,Signed-off-by: Chris Laprun <claprun@redhat.com>

refactor: add default implementation for name()

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/DependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/NameSetter.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/AbstractDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/AbstractEventSourceHolderDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/AbstractWorkflowExecutor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/DefaultManagedWorkflow.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/DefaultWorkflow.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/DependentResourceNode.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowBuilder.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowResult.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/ControllerConfigurationOverriderTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/dependent/DependentResourceConfigurationResolverTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/EmptyTestDependentResource.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/AbstractWorkflowExecutorTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowBuilderTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowReconcileExecutorTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowTest.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/config/BaseConfigurationServiceTest.java

- use this name when throwing aggregate exception

feat: move name is directly to dependent resource

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ExecutorServiceManager.java

If the workflows are not used in reconciliation and executor won't be initialized.

improve: lazy init workflow executor

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverrider.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ExecutorServiceManager.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/EventProcessorTest.java

Note that it was a fixed thread pool also now, just it was confusing with min and max values,

improve: use fixed thread pool explicitly

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/Utils.java

fix: date parsing after 8.0.0 release of git-commit-id

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/Utils.java

refactor: make loadFromProperties private

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/BaseConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/workflow/WorkflowSpec.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/ManagedWorkflowSupport.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/ManagedWorkflowTest.java

refactor: make WorkflowSpec an interface

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcher.java
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/deployment-with-managed-fields-additional-controller.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/nginx-deployment.yaml

fix: ignore server managed fields for SSA matching

---

docs/documentation/v5-0-migration.md
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverrider.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverriderTest.java

refactor: remove deprecated getTerminationTimeoutSeconds and associated

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/ManagedInformerEventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/TemporaryResourceCache.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerEventSourceTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/informer/TemporaryResourceCacheTest.java

closes: #2314
If during a creation the events for both the add and the deletion occur before the resource is being added to the temporary cache, the temporary cache moves backwards in a way that may not resolve itself.
The approach here is to use tombstones to track deletions. The benefit of this approach is that it keeps the logic encapsulated to the TemporaryResourceCache. The drawback is that we're only guessing about how long to retain the tombstones.
The other approach would look more similar to event recording, which is notify the cache that a create is happening prior to when it starts so that deletions / tombstones can gathered for that specific resource.

fix: using tombstones to account for rapid deletion

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/Utils.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/GenericKubernetesDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResource.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/AbstractWorkflowExecutorTest.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/bulkdependent/ConfigMapDeleterBulkDependentResource.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/complexdependent/dependent/BaseDependentResource.java

Fixes #2311
Overriding getPrimaryResourceType should allow to make things work even
in deeper hierarchies.

feat: handle clustered resource on secondary to primary mapper init

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventProcessor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcher.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/ResourceState.java

This should fix the related issue when on startup theoretically an event can be received when the processor is starting. Considering:
- On startup event received while EventProcess is not started yet
- EventProcessor starts and submits all the events (distinguished by resource id) to reconcile
- But mean while a new event is received for a certain resource that was also getting submitted by the start operation

fix: processor concurrency issue on startup

---

pom.xml

 fix: remove now unneeded okhttp dependency override, wrong comment 

---

.github/workflows/e2e-test.yml
pom.xml

- **fix: typo**
- **fix: allow empty tags**
- **feat: run spotless on compile**

feat: run spotless on compile

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcher.java

it can happen that other controller added finalizer, so the logging is misleading

fix: remove invalid log message

---

docsy/content/en/_index.md

fixes: typos, wording

---

docsy/content/en/docs/dependent-resources/_index.md

docs: fixing link typo

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/BaseConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverrider.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/DefaultResourceClassResolver.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ResourceClassResolver.java

The class resolving mechanism is only needed in that class right now

refactor: move getResourceClassResolver to BaseConfigurationService

---

operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/LocallyRunOperatorExtension.java

Apply the CRD using the SSA method in LocallyRunOperationExtension

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/GenericKubernetesResourceMatcher.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/GenericResourceUpdater.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResource.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/GenericKubernetesResourceMatcherTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/GenericResourceUpdaterTest.java

Currently there wast just one `UpdateMatcher` implementation, while it was explicitly in the code that SSA is handled differently.
This PR removes the updateMatcher concept, and makes it explicit that SSA uses the ssa matcher and SSA updater, and also the same holds for the generic matcher and updater.
While I don't disagree with the updateMatcher concept there will be no other combinations than these two.

refactor: `updateMatcher` removal

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/AbstractConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/DependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/health/EventSourceHealthIndicator.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/health/Status.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/AbstractDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/BulkDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/DependentResourceWithExplicitState.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/CRDPresentActivationCondition.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/EventSource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/EventSourceStartPriority.java

chore(docs): add some javadoc

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/DependentResource.java

fix: improper use of @link

---

operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/AbstractOperatorExtension.java

Use server-side apply to create the namespace used for integration test. This, combined with `withNamespaceNameSupplier`, allows the use of a preconfigured namespace for integration tests. We need this because in our particular case some third-party infrastructure cannot be configured at the time of namespace creation and must be set up in advance.

Use SSA to create namespace and infra for integration test

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java
operator-framework/src/main/java/io/javaoperatorsdk/operator/config/runtime/TypeParameterResolver.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/standalonedependent/StandaloneDependentTestReconciler.java

I found some typos and "the the" in comments and error messages.

Fix typos in comments and error messages

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/BulkDependentResource.java

chore: update comment to reflect change in interface

---

docsy/content/en/docs/features/_index.md

Updated the example of registering an event source and also the link.
Previous example:
- Had broken link
- Returned List instead of Map
- Used name `configMapEventSource `, but was apparently for `Deployment`
- Had apparent copy/paste error around lines 508-509
Updated example:
- Omits some details of the actual linked code
- Increased indentation

chore: update example of registering an event source

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/Cleaner.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/Controller.java

Reconciler has this in the signature too. It is completely fine to throw exception
from this method.

improve: cleaner throws Exception

---

operator-framework/src/test/java/io/javaoperatorsdk/operator/IntegrationTestConstants.java

fix: integration test GC timeout on kube 1.31.0

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowBuilder.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowCleanupExecutorTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowReconcileExecutorTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowTest.java
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageDependentsWorkflowReconciler.java
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageStandaloneDependentsReconciler.java

feat: explicit node configuration in WorkflowBuilder

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverrider.java

refactor: rename method more appropriately

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcher.java

resolved: #2492 
Output diff data in text format
```
{data={key1=val1}, metadata={ownerReferences=[{name=kube-root-ca.crt, uid=1ef74cb4-dbbd-45ef-9caf-aa76186594ea, apiVersion=v1, kind=ConfigMap}]}}
{metadata={ownerReferences=[{apiVersion=v1, kind=ConfigMap, name=kube-root-ca.crt, uid=1ef74cb4-dbbd-45ef-9caf-aa76186594ea}]}, data={key1=different value}}
```
- problem : It's difficult to compare
Output diff data in yml format
```yml
data:
key1: "val1"
metadata:
ownerReferences:
- name: "kube-root-ca.crt"
uid: "1ef74cb4-dbbd-45ef-9caf-aa76186594ea"
apiVersion: "v1"
kind: "ConfigMap"
---
metadata:
ownerReferences:
- apiVersion: "v1"
kind: "ConfigMap"
name: "kube-root-ca.crt"
uid: "1ef74cb4-dbbd-45ef-9caf-aa76186594ea"
data:
key1: "different value"
```
If the user sorts fields through Jackson …

feat: print diff resource as yaml

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/AbstractDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResource.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/dependent/externalstate/ExternalWithStateDependentResource.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/dependent/multipledrsametypenodiscriminator/MultipleManagedDependentNoDiscriminatorConfigMap1.java

improve: naming target resource selector method

---

operator-framework-core/pom.xml
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcher.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcherTest.java
pom.xml

Based on [this](https://github.com/operator-framework/java-operator-sdk/pull/2542#issuecomment-2387669854) comment.
Diff is calculated and printed only if there is a mismatch between actual and desired state and logger is enabled for the debug level. Here is the sample output:
```
2024-10-02 16:38:42,233 1 i.j.o.p.d.k.SSABasedGenericKubernetesResourceMatcher [DEBUG] Diff between actual and desired state for resource: ConfigMap with name: test1 in namespace: default is: 
--- 
+++ 
@@ -2,3 +2,3 @@
data:
-  key1: "val1"
+  key1: "different value"
metadata:
```

feat: improve diff logging

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/AbstractWorkflowExecutor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowReconcileExecutor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowResult.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowReconcileExecutorTest.java

fix: race condition in workflow reconciler

---

.github/workflows/build.yml
.github/workflows/e2e-test.yml
.github/workflows/fabric8-next-version-schedule.yml
.github/workflows/integration-tests.yml
.github/workflows/pr.yml
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowReconcileExecutorTest.java
operator-framework/pom.xml
operator-framework/src/test/java/io/javaoperatorsdk/operator/baseapi/clusterscopedresource/ClusterScopedResourceIT.java
pom.xml

feat(ci): split integration tests execution by category

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/managed/DefaultManagedDependentResourceContext.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/Controller.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/DefaultWorkflow.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowBuilder.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowCleanupExecutorTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowReconcileExecutorTest.java

fix: managed workflow result is available even when exception is thrown

---

operator-framework-core/pom.xml
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/ResourceRequirementsSanitizer.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcher.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/ResourceRequirementsSanitizerTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcherTest.java
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-ds-resources-desired-update.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-ds-resources-desired.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-ds-resources.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-rs-resources-desired-update.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-rs-resources-desired.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-rs-resources.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-resources-desired-update.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-resources-desired.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-resources.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-volumeclaimtemplates-desired-add.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-volumeclaimtemplates-desired-update.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-volumeclaimtemplates-desired-with-status-mismatch.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-volumeclaimtemplates-desired-with-status.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-volumeclaimtemplates-desired-with-volumemode-mismatch.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-volumeclaimtemplates-desired-with-volumemode.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-volumeclaimtemplates-desired.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-volumeclaimtemplates.yaml

Fixes #2509
* Branch `next`
* Branch `bugfix/2509-ssa-matcher-quantity/next`

Fix infinite resource updates due to canonical format conversion of resource requirements

---

operator-framework-core/pom.xml
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/ResourceRequirementsSanitizer.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcher.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/ResourceRequirementsSanitizerTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcherTest.java
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-ds-resources-desired-update.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-ds-resources-desired.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-ds-resources.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-rs-resources-desired-update.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-rs-resources-desired.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-rs-resources.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-resources-desired-update.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-resources-desired.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-resources.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-volumeclaimtemplates-desired-add.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-volumeclaimtemplates-desired-update.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-volumeclaimtemplates-desired-with-status-mismatch.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-volumeclaimtemplates-desired-with-status.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-volumeclaimtemplates-desired-with-volumemode-mismatch.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-volumeclaimtemplates-desired-with-volumemode.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-volumeclaimtemplates-desired.yaml
operator-framework-core/src/test/resources/io/javaoperatorsdk/operator/processing/dependent/kubernetes/sample-sts-volumeclaimtemplates.yaml

Backport of #2565
I've cherry-picked the commits on the main branch. There were some merge conflicts in `SSABasedGenericKubernetesResourceMatcher` due to the different Java versions and a other differences in the class that I cleaned up in `next`. Also some tests from `next` are not yet in `SSABasedGenericKubernetesResourceMatcherTest`, which lead to a minimal merge conflict as well. So nothing unexpected or hard to resolve.

[BACKPORT] Fix infinite resource updates due to canonical format conversion of resource requirements

---

operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/LocallyRunOperatorExtension.java
operator-framework/src/test/crd/test.crd
operator-framework/src/test/java/io/javaoperatorsdk/operator/CRDMappingInTestExtensionIT.java

This is useful when using a contract-first approach where the Java
classes are generated from the CRD instead of the reverse.
Fixes #2561

feat: allow manually specifying CRDs in test extension

---

docs/content/en/docs/migration/v2-migration.md
docs/content/en/docs/migration/v3-1-migration.md
docs/content/en/docs/migration/v3-migration.md
docs/content/en/docs/migration/v4-3-migration.md
docs/content/en/docs/migration/v4-4-migration.md
docs/content/en/docs/migration/v4-5-migration.md

The explicit title caused to show the title in double

fix: docs double header in migration docs

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/managed/DefaultManagedDependentResourceContext.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/managed/ManagedDependentResourceContext.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/reconciler/dependent/managed/DefaultManagedDependentResourceContextTest.java

The javadoc  of `ManagedDependentResourceContext#put` describe it as returning `Optional`. The implementation returns an `Optional` but casts it to T, so it is currently a compile error to write:
```
Optional<String> result = new ManagedDependentResourceContext().put("key", "value");
```
Using the method as declared results in a ClassCastException:
```
DefaultManagedDependentResourceContext context = new DefaultManagedDependentResourceContext();
context.put("key", "value");
String actual = context.put("key", "valueB");
```
fails with:
```
java.lang.ClassCastException: class java.util.Optional cannot be cast to class java.lang.String (java.util.Optional and java.lang.String are in module java.base of loader 'bootstrap')
```
The user can cast to get at the Optional like `Optional<String> …

Method signature mismatched with javadoc and implementation

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/managed/DefaultManagedWorkflowAndDependentResourceContext.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/managed/ManagedWorkflowAndDependentResourceContext.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/Controller.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/AbstractWorkflowExecutor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/BaseWorkflowResult.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/DefaultWorkflowCleanupResult.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/DefaultWorkflowReconcileResult.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowCleanupExecutor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowCleanupResult.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowReconcileExecutor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowReconcileResult.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowResult.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/workflow/BaseWorkflowResultTest.java

feat: return result when calling workflow explicitly

---

bootstrapper-maven-plugin/src/main/resources/templates/pom.xml
operator-framework/pom.xml
operator-framework/src/test/java/io/javaoperatorsdk/operator/CRDMappingInTestExtensionIT.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/config/runtime/TestCustomResource.java
sample-operators/mysql-schema/pom.xml
sample-operators/tomcat-operator/pom.xml
sample-operators/webpage/pom.xml

Fix CRD-Generator tests and examples for #2540
See also https://github.com/fabric8io/kubernetes-client/issues/6683
/cc @metacosm

Fix CRD-Generator tests and examples

---

bootstrapper-maven-plugin/src/main/resources/templates/pom.xml
caffeine-bounded-cache-support/pom.xml
docs/content/en/docs/migration/v5-0-migration.md
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/VersionTest.java
operator-framework/pom.xml
pom.xml
sample-operators/mysql-schema/pom.xml
sample-operators/tomcat-operator/pom.xml
sample-operators/webpage/pom.xml

Signed-off-by: Bernhard Strähle <bernhard.straehle@gmail.com>

chore: update to Fabric8 7.0-SNAPSHOT & replace APT by maven plugin

---

.github/workflows/build.yml
.github/workflows/e2e-test.yml
.github/workflows/integration-tests.yml

bump: minikube version and add k8s version 1.32.0

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/managed/DefaultManagedWorkflowAndDependentResourceContext.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/managed/ManagedWorkflowAndDependentResourceContext.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/dependent/bulkdependent/condition/ManagedBulkDependentWithReadyConditionReconciler.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/dependent/bulkdependent/readonly/ReadOnlyBulkReconciler.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/workflow/complexdependent/ComplexWorkflowReconciler.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/workflow/workflowallfeature/WorkflowAllFeatureReconciler.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/workflow/workflowsilentexceptionhandling/HandleWorkflowExceptionsInReconcilerReconciler.java

improve: optional workflow result

---

docs/content/en/blog/releases/v5-release.md
docs/content/en/docs/features/_index.md
docs/content/en/docs/workflows/_index.md

docs: v5.0.0 related fixes from beta feedback

---

README.md

docs: changed glue link

---

operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/LocallyRunOperatorExtension.java
operator-framework-junit5/src/test/crd/test.crd
operator-framework-junit5/src/test/java/io/javaoperatorsdk/operator/junit/LocallyRunOperatorExtensionTest.java
operator-framework-junit5/src/test/resources/crd/test.crd
operator-framework-junit5/src/test/resources/log4j2.xml
operator-framework/src/test/crd/test.crd
operator-framework/src/test/java/io/javaoperatorsdk/operator/CRDMappingInTestExtensionIT.java
pom.xml

fix: ensure manually defined CRDs are considered before generated ones

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/informer/InformerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/informer/InformerEventSourceConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentConverter.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/ControllerConfigurationOverriderTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/InformerConfigurationTest.java
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageDependentsWorkflowReconciler.java
sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageStandaloneDependentsReconciler.java

improve: naming InformerConfiguration build

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/Controller.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/ControllerTest.java

fix: explicit workflow invovation cleanup issue

---

pom.xml

This allows running maven in submodules, for instance to run only some tests.

refactor: move spotless to a profile active only in the root directory

---

operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/LocallyRunOperatorExtension.java
sample-operators/tomcat-operator/src/test/java/io/javaoperatorsdk/operator/sample/TomcatOperatorE2E.java

Before:
```
$ mvn clean install -Pintegration-tests
...
$ kubectl get crds | wc -l
83
```
With this PR:
```
$ mvn clean install -Pintegration-tests
...
$ kubectl get crds | wc -l
No resources found
0
```

fix: add clean up of applied CRDs after tests

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/DefaultContext.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcher.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcherTest.java

fix: explicit workflow invocation uses the same resource intance that reconcile api

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/DefaultContext.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcher.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcherTest.java
operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/LocallyRunOperatorExtension.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/baseapi/changenamespace/ChangeNamespaceTestReconciler.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/baseapi/statuspatchnonlocking/StatusPatchLockingReconciler.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/baseapi/statuspatchnonlocking/StatusPatchNotLockingForNonSSAIT.java

fix: patch version handling

---

.github/workflows/build.yml
.github/workflows/integration-tests.yml
.github/workflows/pr.yml

Fixes https://github.com/operator-framework/java-operator-sdk/issues/2698
Essentially saves the matrix for the individual it-category tests.

fix: GH actions revert to use less Minikube downloads

---

operator-framework-junit5/src/main/java/io/javaoperatorsdk/operator/junit/LocallyRunOperatorExtension.java

Fixes #2728
@csviri also adjusted the default timeout as it might help in CI.

fix: don't fail test if the CRD cannot be deleted

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/KubernetesResourceDeletedCondition.java

This way it is easier to reason about the resource deletion.

improve: more strict delete condition

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/GroupVersionKind.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/GroupVersionKindPlural.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/GroupVersionKindTest.java

fix: a GVKP with no plural should be equivalent to the same GVK

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/Mappers.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/informer/MappersTest.java

The HasMetadata.getApiVersion(primaryResourceType) method return "/v1" for the ConfigMap type. Since the K8s owner reference uses "v1" instead, the secondary resource of a primary ConfigMap will not be tracked correctly.
Proposed fix for #2723

Fix apiVersion match for standard K8s resources

---

.github/workflows/build.yml
.github/workflows/pr.yml

feat(ci): build with Java 21 and 24

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/ControllerConfiguration.java

docs: explanation for max maxReconciliationInterval

---

docs/content/en/docs/documentation/error-handling-retries.md

docs: retry doc fixes

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventProcessor.java

A proposal to further refine the exception logging so that it uses INFO (mostly ignorable), WARN (may recover), ERROR (won't recover).
closes: #2747

fix: refine retryAwareErrorLogging

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcher.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcherTest.java

This PR addresses #2509 and makes it easier to customize the matching logic in SSABasedGenericKubernetesResourceMatcher without having to clone the entire class just to override its behavior.
The change is based on the solution suggested by @Donnerbart [here](https://github.com/operator-framework/java-operator-sdk/issues/2553#issuecomment-2493712071), but it avoids passing the primary resource directly in order to keep the existing matches method signature unchanged. If the primary resource is needed, it can instead be made available through the context.
The implementation introduces a new protected matches method that handles the actual comparison. The public matches method delegates to this new method, making it easy to override in subclasses.

Improve customizability of SSABasedGenericKubernetesResourceMacher

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventProcessor.java

fix: event marking bug

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcher.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/baseapi/concurrentfinalizerremoval/ConcurrentFinalizerRemovalCustomResource.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/baseapi/concurrentfinalizerremoval/ConcurrentFinalizerRemovalIT.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/baseapi/concurrentfinalizerremoval/ConcurrentFinalizerRemovalReconciler1.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/baseapi/concurrentfinalizerremoval/ConcurrentFinalizerRemovalReconciler2.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/baseapi/concurrentfinalizerremoval/ConcurrentFinalizerRemovalSpec.java

this can happen if there are multiple finalizers present and multiple reconilers competent to remove their finalizer, since we remove the finalizer with JSON Patch

fix: retry finalizer removal on http 422

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/Context.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/DefaultContext.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcher.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/reconciler/DefaultContextTest.java

Solves a remaining issue from: #2553

Make primary resource accessible from Context

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependent.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentConverter.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResourceConfig.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResourceConfigBuilder.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcherTest.java

feat: allow easier configuration of matcher

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverrider.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/KubernetesDependentResource.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcher.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/dependent/prevblocklist/DeploymentDependent.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/dependent/prevblocklist/PrevAnnotationBlockCustomResource.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/dependent/prevblocklist/PrevAnnotationBlockReconciler.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/dependent/prevblocklist/PrevAnnotationBlockReconcilerIT.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/dependent/prevblocklist/PrevAnnotationBlockSpec.java

improve: blocklist of problematic resources for previous version annotation

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/PodTemplateSpecSanitizer.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/SSABasedGenericKubernetesResourceMatcher.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/PodTemplateSpecSanitizerTest.java
operator-framework/src/test/resources/io/javaoperatorsdk/operator/statefulset.yaml

Fixes https://github.com/operator-framework/java-operator-sdk/issues/2802

Fix infinite resource updates due empty EnvVars

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverrider.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverriderTest.java

fix: pool size configuration

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/PrimaryUpdateAndCacheUtils.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/TemporaryResourceCache.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/reconciler/PrimaryUpdateAndCacheUtilsTest.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/baseapi/statuscache/StatusPatchCacheCustomResource.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/baseapi/statuscache/StatusPatchCacheIT.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/baseapi/statuscache/StatusPatchCacheReconciler.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/baseapi/statuscache/StatusPatchCacheSpec.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/baseapi/statuscache/StatusPatchCacheStatus.java

Reading from API server was not correct, this works in all cases only if the informer cache has the up to date resources.
If we don't have the up to date resource in the cache, and don't do the update based on that, we cannot say for sure if we can remove the resource for the next event or not from overlay cache.

fix: primary cache utils mechanism

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/informer/InformerEventSourceConfiguration.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/config/ControllerConfigurationOverriderTest.java

improve: add InformerEventSourceConfiguration withNamespaces overloaded version

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/informer/Field.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/informer/FieldSelector.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/informer/FieldSelectorBuilder.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/informer/Informer.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/informer/InformerConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/informer/InformerEventSourceConfiguration.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerManager.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/baseapi/fieldselector/FieldSelectorIT.java
operator-framework/src/test/java/io/javaoperatorsdk/operator/baseapi/fieldselector/FieldSelectorTestReconciler.java

closes https://github.com/operator-framework/java-operator-sdk/issues/2813

feat: field selectors support for InformerEventSource

---

docs/content/en/docs/faq/_index.md

docs: fix links and mention status utility in faq

---

docs/content/en/docs/faq/_index.md

docs: add faq entry regarding event filtering

---

.github/workflows/build.yml
.github/workflows/e2e-test.yml
.github/workflows/integration-tests.yml

Currently integration tests are being throttled, this should not happen when github token is used.
It seems that sub-workflows it should be passed or used as `github.token`, see here:
https://docs.github.com/en/actions/tutorials/use-github_token-in-workflows#using-the-github_token-in-a-workflow

fix: minikube setup does not use github token

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/WorkflowReconcileExecutor.java

Fix for a problem described in #2885. 
The changed code causes that when `visited` flag is changed to true, we are sure that readyPostconditionResult was checked before. In previous version, `visited` flag set to true and readyPostconditionResult equals null could describe two situations:
1. A resource was visited and its readyPostcondition is null.
2. A resource was visited and its readyPostcondition exists, but wasn't wasn't checked (race condition).
The changed code doesn't let the second situation to happen.

fix: Resolve race condition between visited flag and result of ready postcondition

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventProcessor.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/ResourceStateManager.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/EventProcessorTest.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/ResourceStateManagerTest.java

In general we cleanup state on delete event, so although in practice this probably not causing
issues in theory it can happen that we receive events where there is no related custom resource.
What effectivel means a memory leak, since that state never cleaned up - again it is more theoretical than practical issues, since it practice usually events are propagated related to a custom resource (or based on that).
This PR fixes it in a way that it checks that when state is created it is alway related to a resource event (thus for primary / custom resource). In that way avoiding that state is created without a primary resource. 

fix: create state only on resource event

---

docs/content/en/docs/documentation/observability.md
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/monitoring/AggregatedMetrics.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/api/monitoring/AggregatedMetricsTest.java

Partially fixes #2884
Alternative to #2912
See https://github.com/operator-framework/java-operator-sdk/pull/2912#issuecomment-3228683758

Add AggregatedMetrics to support multiple Metrics implementations

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/Experimental.java

Annotation would serve to mark experimental features.

feat: add experimental annotation

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/Operator.java
operator-framework-core/src/test/java/io/javaoperatorsdk/operator/OperatorTest.java

refactor: avoid unneeded initializations in injection contexts

---

operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/DependentResourceFactory.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/DefaultManagedWorkflow.java
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/workflow/DependentResourceNode.java

We want to provide CDI beans in the `Condition` subclasses as requested in https://github.com/quarkiverse/quarkus-operator-sdk/issues/720.

feat: allow DependentResourceNode creation override

---

bootstrapper-maven-plugin/src/main/resources/templates/pom.xml

When you start the Runner of the bootstrapped code no logs do appear in the terminal.
Upgrading slf4j fixes this problem.

fix: upgrade slf4j in bootstrapped code

---

docs/content/en/docs/documentation/_index.md
docs/content/en/docs/documentation/access-resources.md
docs/content/en/docs/documentation/working-with-es-caches.md
operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/SecondaryToPrimaryMapper.java

docs: add page to describe cache access model
